import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import getSession from "@/lib/data/auth/get-session";
import { getUserProfileIdCached } from "@/lib/cache/users";
import { hasRole, resolveNextPath } from "@/lib/utils";
import {
  BadgeInfo,
  CalendarDays,
  Mail,
  MapPin,
  Link as LinkIcon,
  Users,
} from "lucide-react";
import { notFound, redirect } from "next/navigation";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import BackButton from "@/app/_components/BackButton";
import ContractDetailClient from "./ContractDetailClient";
import { useMemo } from "react";
import { GREEN_TICK_ICON } from "@/lib/constants";
import UplodPdf from "../_components/UploadPdf";
import Image from "next/image";
import DocuSignButton from "../../eventi/_components/create/DocuSignButton";

type ContractDetailPageProps = {
  params?: Promise<{ id: string }>;
  searchParams?: Promise<{
    stage?: string;
    data?: string; // 👈 ADD THIS
  }>;
};

type HistoryItem = {
  date: string;
  time: string;
  title: string;
  description?: string;
  type: "archived" | "success";
};

type ContractDetailStatus =
  | "missing"
  | "to-sign"
  | "signed"
  | "refused"
  | "error"
  | "archived";

const mockContract = {
  id: "c-123",
  statusDate: "13/11/25",
  artistHandle: "@bobjohnson",
  artistName: "Bob Johnson",
  venueName: "Club “Maestro”",
  date: "27/05/2025",
  time: "14:00 - 16:30",
  tourManager: "Anna Trevisan",
  tourManagerEmail: "trevisana@gmail.com",
  consultantEmail: "robert.fox.events@gmail.com",
  adminEmail: "brooklyn@gmail.com",
  managerName: "Anna Trevisan",
  managerEmail: "mail@wow.com",
  downloadLabel: "Contract.pdf",
};

const FLOW_STATES: Record<
  ContractDetailStatus,
  {
    statusLabel: string;
    badge: { dot: string; bg: string };
    actionsDisabled: boolean;
    hasFile: boolean;
    showDelete: boolean;
    showDownload: boolean;
    warning?: string;
    requireTourManager: boolean;
    history: {
      id: string;
      title: string;
      description?: string;
      date: string;
      time: string;
      link?: string;
    }[];
  }
> = {
  missing: {
    statusLabel: "Missing data",
    badge: {
      dot: "bg-amber-500",
      bg: "bg-amber-50 text-amber-700 border-amber-200",
    },
    actionsDisabled: true,
    hasFile: false,
    showDelete: false,
    showDownload: false,
    warning:
      "The contract cannot be generated because the event data is incomplete.",
    requireTourManager: true,
    history: [
      {
        id: "h1",
        title: "Status changed to “Missing data”",
        description: "Auto status change",
        date: "13/11/25",
        time: "9:31 AM",
      },
    ],
  },

  "to-sign": {
    statusLabel: "To sign",
    badge: { dot: "bg-sky-500", bg: "bg-sky-50 text-sky-700 border-sky-100" },
    actionsDisabled: false,
    hasFile: true,
    showDelete: true,
    showDownload: true,
    requireTourManager: false,
    history: [
      {
        id: "h2",
        title: "Status changed to “To Sign”",
        description: "Sent to DocuSign",
        date: "13/11/25",
        time: "9:31 AM",
        link: "View",
      },
      {
        id: "h3",
        title: "Contract autogenerated",
        date: "13/11/25",
        time: "9:30 AM",
      },
    ],
  },

  signed: {
    statusLabel: "Signed",
    badge: {
      dot: "bg-emerald-500",
      bg: "bg-emerald-50 text-emerald-700 border-emerald-100",
    },
    actionsDisabled: false,
    hasFile: true,
    showDelete: false,
    showDownload: true,
    requireTourManager: false,
    history: [
      {
        id: "h4",
        title: "Contract signed",
        description: "Signed via DocuSign",
        date: "14/11/25",
        time: "3:15 PM",
      },
    ],
  },

  refused: {
    statusLabel: "Refused",
    badge: {
      dot: "bg-rose-500",
      bg: "bg-rose-50 text-rose-700 border-rose-100",
    },
    actionsDisabled: false,
    hasFile: true,
    showDelete: true,
    showDownload: true,
    requireTourManager: false,
    history: [
      {
        id: "h5",
        title: "Contract refused",
        description: "Signer refused the contract",
        date: "14/11/25",
        time: "10:00 AM",
      },
    ],
  },

  error: {
    statusLabel: "Error",
    badge: { dot: "bg-red-500", bg: "bg-red-50 text-red-700 border-red-100" },
    actionsDisabled: false,
    hasFile: true,
    showDelete: true,
    showDownload: true,
    requireTourManager: false,
    history: [
      {
        id: "h6",
        title: "DocuSign error",
        description: "Delivery failed",
        date: "14/11/25",
        time: "11:20 AM",
      },
    ],
  },

  archived: {
    statusLabel: "Archived",
    badge: {
      dot: "bg-zinc-400",
      bg: "bg-zinc-50 text-zinc-600 border-zinc-200",
    },
    actionsDisabled: true,
    hasFile: true,
    showDelete: false,
    showDownload: true,
    requireTourManager: false,
    history: [
      {
        id: "h7",
        title: "Contract archived",
        description: "Completed and archived",
        date: "15/11/25",
        time: "9:00 AM",
      },
    ],
  },
};

export default async function ContractDetailPage({
  params,
  searchParams,
}: ContractDetailPageProps) {
  const { session, user } = await getSession();

  if (!session || !user || user.banned) {
    redirect("/logout");
  }

  const profileId = await getUserProfileIdCached(user.id);
  const target = resolveNextPath({ user, hasProfile: Boolean(profileId) });
  if (target) redirect(target);

  if (!hasRole(user, ["admin", "artist-manager", "venue-manager"])) {
    notFound();
  }

  await params;
  const sp = await searchParams;
  if (!sp?.data) notFound();
  const payload = JSON.parse(decodeURIComponent(sp.data));
  console.log(payload?.artist?.avatarUrl, "payload-------------");
  const stage = (sp?.stage as ContractDetailStatus | undefined) ?? "missing";
  const flow = FLOW_STATES[stage] ?? FLOW_STATES["missing"];
  const statusLabel = flow.statusLabel;
  const statusColor = flow.badge;

  const statusOptions: { value: ContractDetailStatus; label: string }[] = [
    { value: "to-sign", label: "To sign" },
    { value: "signed", label: "Signed" },
    { value: "refused", label: "Refused" },
    { value: "error", label: "Error" },
    { value: "archived", label: "Archived" },
  ];

  function formatDateAndTime(
  availability: {
    startDate: string;
    endDate: string;
  } | null
): { date: string; time: string } {
  if (!availability) {
    return { date: "—", time: "—" };
  }

  const start = new Date(availability.startDate);
  const end = new Date(availability.endDate);

  const date = start.toLocaleDateString("it-IT", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });

  const time = `${start.toLocaleTimeString("it-IT", {
    hour: "2-digit",
    minute: "2-digit",
  })} – ${end.toLocaleTimeString("it-IT", {
    hour: "2-digit",
    minute: "2-digit",
  })}`;

  return { date, time };
}
const { date, time } = formatDateAndTime(payload?.availability ?? null);

  const historyData: HistoryItem[] = Array.isArray(payload.history)
    ? payload.history.map((h: any) => {
        const createdAt = new Date(h.createdAt);

        return {
          date: createdAt.toLocaleDateString("it-IT"),
          time: createdAt.toLocaleTimeString("en-US", {
            hour: "2-digit",
            minute: "2-digit",
            hour12: true,
          }),
          title: h.fromStatus
            ? `Status changed from "${h.fromStatus}" to "${h.toStatus}"`
            : "Contract created",
          description: h.note ?? "No description available",
          type: h.toStatus === "voided" ? "archived" : "success",
        };
      })
    : [];

  console.log(payload, "payload-------------------------");
  return (
    <div className="h-full w-full bg-zinc-50 px-4 py-6 md:p-6 flex flex-col gap-6">
      <div className="flex flex-wrap justify-between items-center gap-3">
        {/* <h1 className='text-2xl font-bold'>Contracts</h1> */}
        <BackButton />
        <div className="flex items-center gap-2">
          <Button variant="secondary" size="sm" disabled={flow.actionsDisabled}>
            {stage === "missing" ? "Generate" : "Regenerate"}
          </Button>
          {/* <DocuSignButton  event={event} /> */}
          
          <Button variant="default" size="sm" disabled={flow.actionsDisabled}>
            Send to DocuSign
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-[2fr_1fr] gap-4">
        <Card className="bg-white shadow-sm border-zinc-200">
          <CardContent className="flex flex-col gap-4">
            <div className="flex flex-wrap justify-between gap-4">
              <div className="flex flex-col gap-2">
                <div className="flex items-center gap-3">
                  <img
                    src={payload?.artist?.avatarUrl}
                    alt="Avatar"
                    className="size-11 rounded-full object-cover bg-zinc-200"
                  />
                  <div className="flex flex-col">
                    <div className="font-semibold text-lg">
                      {payload.stageName}
                    </div>
                    <div className="text-sm text-zinc-500">
                      {payload.artistName}
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-3 text-sm text-zinc-600">
                  <span className="flex items-center gap-1">
                    <MapPin className="size-4 text-zinc-400" />
                    {payload?.venue?.name}
                  </span>
                  <span className="flex items-center gap-1">
                    <CalendarDays className="size-4 text-zinc-400" />
                    {date}
                    </span>
                  <span className="flex items-center gap-1">
                    <Users className="size-4 text-zinc-400" />
                    {time}
                    </span>
                </div>
              </div>

              <div className="flex flex-col items-end gap-2 min-w-[220px]">
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button
                      variant="outline"
                      size="sm"
                      className={`gap-2 px-5 h-11 rounded-full font-semibold text-base border-amber-200 bg-white shadow-[0_1px_2px_rgba(16,24,40,0.05)] ${statusColor.bg}`}
                    >
                      <span
                        className={`size-3 rounded-full ${statusColor.dot}`}
                      />
                      {statusLabel}
                      <BadgeInfo className="size-4 text-amber-600" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end" className="min-w-[200px]">
                    {statusOptions.map((opt) => (
                      <DropdownMenuItem
                        key={opt.value}
                        className={
                          opt.value === stage
                            ? "font-semibold text-amber-700"
                            : ""
                        }
                      >
                        {opt.label}
                      </DropdownMenuItem>
                    ))}
                  </DropdownMenuContent>
                </DropdownMenu>
                <div className="text-xs text-zinc-500">
                  Status changed on {mockContract.statusDate}
                </div>
              </div>
            </div>

            <Separator />

            <div className="flex flex-col gap-3">
              <div className="text-sm font-semibold text-zinc-800">
                Contract file
              </div>
              <UplodPdf />
            </div>

            <Separator />

            <div className="flex flex-wrap items-center gap-3 text-sm text-zinc-600">
              <span className="text-zinc-800 font-semibold">Event details</span>
              <Button variant="link" size="sm"  className="p-0 h-auto text-sm text-sky-700">
                View event details
              </Button>
            </div>

            <div className="flex flex-wrap gap-3 text-xs md:text-sm text-zinc-600">
              <span className="flex items-center gap-1">
                <MapPin className="size-4 text-zinc-400" />
                Locale
              </span>
              <Badge variant="secondary">{payload?.venue?.name}</Badge>
              <Badge variant="secondary">manager</Badge>
              <Badge variant="secondary">{payload?.artist.tourManagerName}</Badge>
            </div>

            <div className="flex flex-wrap gap-2 text-xs text-zinc-500">
              <span className="flex items-center gap-1">
                <Users className="size-4 text-zinc-400" />
                Tour manager
              </span>
              <Badge variant="outline">
                {" "}
                {payload?.artist?.tourManagerName || ""}{" "}
                {payload?.artist?.tourManagerSurname || ""}
              </Badge>
              <Badge variant="outline">Administration</Badge>
              <span className="flex items-center gap-1">
                <Mail className="size-4 text-zinc-400" />
                {payload?.artist?.tourManagerEmail}
              </span>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-white shadow-sm border-zinc-200">
          <CardContent className="flex flex-col gap-4">
            <div className="flex items-center justify-between">
              <div className="text-lg font-semibold">History of changes</div>
            </div>

            <div className="flex flex-col gap-4">
              {historyData.map((item, index) => {
                const isLast = index === historyData.length - 1;

                return (
                  <div
                    key={index}
                    className="grid grid-cols-[60px_1fr] gap-4 relative"
                  >
                    {/* LEFT: DATE + TIME */}
                    <div className="flex flex-col items-center text-center leading-tight">
                      <span className="text-xs font-medium text-zinc-600">
                        {item.date}
                      </span>
                      <span className="text-xs text-zinc-500">{item.time}</span>
                    </div>

                    {/* RIGHT SIDE BLOCK */}
                    <div className="relative pl-6">
                      {!isLast && (
                        <div className="absolute left-[6px] top-4 bottom-[-2px] w-[0.5px] bg-green-600/70"></div>
                      )}

                      <div className="absolute left-0 top-1">
                        {item.type === "archived" ? (
                          <div className="w-3 h-3 border border-zinc-700 rounded-full bg-white"></div>
                        ) : (
                          <img
                            src={GREEN_TICK_ICON}
                            width={12}
                            height={12}
                            alt="Success"
                            className="object-contain"
                          />
                        )}
                      </div>

                      {/* Title */}
                      <div className="text-sm font-medium text-zinc-800">
                        {item.title}
                      </div>

                      {/* Description */}
                      <div className="text-xs text-zinc-500 leading-relaxed mt-1">
                        {item.description}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      </div>

      <Card className="bg-white shadow-sm border-zinc-200">
        <CardContent className="flex flex-col gap-6">
          <div className="flex items-center justify-between">
            <div className="text-lg font-semibold">Details</div>
          </div>

          <ContractDetailClient payload={payload} />
        </CardContent>
      </Card>
    </div>
  );
}
