import { View } from 'react-big-calendar';

export const USER_ROLES = [
  'admin',
  'artist-manager',
  'venue-manager',
  'user',
] as const; // as const = is an immutable array

export type UserRole = (typeof USER_ROLES)[number];

// resend password email
export const RPE_BLOCK_DURATION = 30 * 1000;
export const RPE_BLOCK_STORAGE_NAME = 'rpe_send_at';

export const NAVBAR_LINKS = [
  {
    label: 'Dashboard',
    href: '/dashboard',
    iconSrc: '/images/navbar-icons/dashboard.svg',
    iconAlt: 'icona Dashboard',
    separator: false,
  },
  {
    label: 'Eventi',
    href: '/eventi',
    iconSrc: '/images/navbar-icons/events.svg',
    iconAlt: 'icona Eventi',
    separator: true,
  },
  {
    label: 'Manager artisti',
    href: '/manager-artisti',
    iconSrc: '/images/navbar-icons/manager-artists.svg',
    iconAlt: 'icona Manager artisti',
    separator: false,
  },
  {
    label: 'Artisti',
    href: '/artisti',
    iconSrc: '/images/navbar-icons/artists.svg',
    iconAlt: 'icona Artisti',
    separator: true,
  },
  {
    label: 'Manager locali',
    href: '/manager-locali',
    iconSrc: '/images/navbar-icons/manager-venues.svg',
    iconAlt: 'icona Manager locali',
    separator: false,
  },
  {
    label: 'Locali',
    href: '/locali',
    iconSrc: '/images/navbar-icons/venues.svg',
    iconAlt: 'icona Locali',
    separator: false,
  },
];

export const CALENDAR_VIEWS: View[] = ['day', 'week', 'month'];

// avatar upload
export const AU_LOCAL_STORAGE_KEY = 'au_temporary_url';
export const AU_LOCAL_STORAGE_TTL = 2 * 60 * 60 * 1000; // 2hours;
export const AU_MAX_SIZE_MB = 5;
export const AU_ALLOWED_MIME_TYPES = ['image/jpeg', 'image/png', 'image/webp'];

export const LANGUAGES = [
  { id: 'AA', name: 'Afar' },
  { id: 'AB', name: 'Abcaso' },
  { id: 'AE', name: 'Avestico' },
  { id: 'AF', name: 'Afrikaans' },
  { id: 'AK', name: 'Akan' },
  { id: 'AM', name: 'Amarico' },
  { id: 'AN', name: 'Aragonese' },
  { id: 'AR', name: 'Arabo' },
  { id: 'AS', name: 'Assamese' },
  { id: 'AV', name: 'Avaro' },
  { id: 'AY', name: 'Aymara' },
  { id: 'AZ', name: 'Azerbaigiano' },
  { id: 'BA', name: 'Baschiro' },
  { id: 'BE', name: 'Bielorusso' },
  { id: 'BG', name: 'Bulgaro' },
  { id: 'BH', name: 'Biharo' },
  { id: 'BI', name: 'Bislamo' },
  { id: 'BM', name: 'Bambara' },
  { id: 'BN', name: 'Bengalese' },
  { id: 'BO', name: 'Tibetano' },
  { id: 'BR', name: 'Bretone' },
  { id: 'BS', name: 'Bosniaco' },
  { id: 'CA', name: 'Catalano' },
  { id: 'CE', name: 'Ceceno' },
  { id: 'CH', name: 'Chamorro' },
  { id: 'CO', name: 'Corsico' },
  { id: 'CR', name: 'Cree' },
  { id: 'CS', name: 'Ceco' },
  { id: 'CU', name: 'Slavo ecclesiastico antico' },
  { id: 'CV', name: 'Ciuvascio' },
  { id: 'CY', name: 'Gallese' },
  { id: 'DA', name: 'Danese' },
  { id: 'DE', name: 'Tedesco' },
  { id: 'DV', name: 'Maldiviano' },
  { id: 'DZ', name: 'Dzongkha' },
  { id: 'EE', name: 'Ewe' },
  { id: 'EL', name: 'Greco' },
  { id: 'EN', name: 'Inglese' },
  { id: 'EO', name: 'Esperanto' },
  { id: 'ES', name: 'Spagnolo' },
  { id: 'ET', name: 'Estone' },
  { id: 'EU', name: 'Basco' },
  { id: 'FA', name: 'Persiano' },
  { id: 'FF', name: 'Fula' },
  { id: 'FI', name: 'Finlandese' },
  { id: 'FJ', name: 'Figiano' },
  { id: 'FO', name: 'Faroense' },
  { id: 'FR', name: 'Francese' },
  { id: 'FY', name: 'Frisone occidentale' },
  { id: 'GA', name: 'Irlandese' },
  { id: 'GD', name: 'Gaelico' },
  { id: 'GL', name: 'Galiziano' },
  { id: 'GN', name: 'Guaraní' },
  { id: 'GU', name: 'Gujarati' },
  { id: 'GV', name: 'Mannese' },
  { id: 'HA', name: 'Hausa' },
  { id: 'HE', name: 'Ebraico' },
  { id: 'HI', name: 'Hindi' },
  { id: 'HO', name: 'Hiri Motu' },
  { id: 'HR', name: 'Croato' },
  { id: 'HT', name: 'Haitiano' },
  { id: 'HU', name: 'Ungherese' },
  { id: 'HY', name: 'Armeno' },
  { id: 'HZ', name: 'Herero' },
  { id: 'IA', name: 'Interlingua' },
  { id: 'IN', name: 'Indonesiano' },
  { id: 'IE', name: 'Interlingua (de Wahl)' },
  { id: 'IG', name: 'Igbo' },
  { id: 'II', name: 'Sichuanese' },
  { id: 'IK', name: 'Inupiaq' },
  { id: 'IO', name: 'Ido' },
  { id: 'IS', name: 'Islandese' },
  { id: 'IT', name: 'Italiano' },
  { id: 'IU', name: 'Inuktitut' },
  { id: 'JA', name: 'Giapponese' },
  { id: 'JV', name: 'Giavanese' },
  { id: 'KA', name: 'Georgiano' },
  { id: 'KG', name: 'Kongo' },
  { id: 'KI', name: 'Kikuyu' },
  { id: 'KJ', name: 'Kwanyama' },
  { id: 'KK', name: 'Kazaco' },
  { id: 'KL', name: 'Groenlandese' },
  { id: 'KM', name: 'Cambogiano' },
  { id: 'KN', name: 'Kannada' },
  { id: 'KO', name: 'Coreano' },
  { id: 'KR', name: 'Kanuri' },
  { id: 'KS', name: 'Kashmiri' },
  { id: 'KU', name: 'Curdo' },
  { id: 'KV', name: 'Komi' },
  { id: 'KW', name: 'Cornico' },
  { id: 'KY', name: 'Kirghisa' },
  { id: 'LA', name: 'Latino' },
  { id: 'LB', name: 'Lussemburghese' },
  { id: 'LG', name: 'Luganda' },
  { id: 'LI', name: 'Limburghese' },
  { id: 'LN', name: 'Lingala' },
  { id: 'LO', name: 'Lao' },
  { id: 'LT', name: 'Lituano' },
  { id: 'LU', name: 'Luba-Katanga' },
  { id: 'LV', name: 'Lettone' },
  { id: 'MG', name: 'Malgascio' },
  { id: 'MH', name: 'Marshallese' },
  { id: 'MI', name: 'Māori' },
  { id: 'MK', name: 'Macedone' },
  { id: 'ML', name: 'Malayalam' },
  { id: 'MN', name: 'Mongolo' },
  { id: 'MO', name: 'Moldavo' },
  { id: 'MR', name: 'Marathi' },
  { id: 'MS', name: 'Malese' },
  { id: 'MT', name: 'Maltese' },
  { id: 'MY', name: 'Birmano' },
  { id: 'NA', name: 'Nauruano' },
  { id: 'NB', name: 'Norvegese Bokmål' },
  { id: 'ND', name: 'Ndebele del nord' },
  { id: 'NE', name: 'Nepalese' },
  { id: 'NG', name: 'Ndongo' },
  { id: 'NL', name: 'Olandese' },
  { id: 'NN', name: 'Norvegese Nynorsk' },
  { id: 'NO', name: 'Norvegese' },
  { id: 'NR', name: 'Ndebele del sud' },
  { id: 'NV', name: 'Navajo' },
  { id: 'NY', name: 'Chewa' },
  { id: 'OC', name: 'Occitano' },
  { id: 'OJ', name: 'Ojibwe' },
  { id: 'OM', name: 'Oromonico' },
  { id: 'OR', name: 'Odia' },
  { id: 'OS', name: 'Osseto' },
  { id: 'PA', name: 'Punjabi' },
  { id: 'PI', name: 'Pāli' },
  { id: 'PL', name: 'Polacco' },
  { id: 'PS', name: 'Pashto' },
  { id: 'PT', name: 'Portoghese' },
  { id: 'QU', name: 'Quechua' },
  { id: 'RM', name: 'Romancio' },
  { id: 'RN', name: 'Kirundi' },
  { id: 'RO', name: 'Rumeno' },
  { id: 'RU', name: 'Russo' },
  { id: 'RW', name: 'Kinyarwanda' },
  { id: 'SA', name: 'Sanscrito' },
  { id: 'SC', name: 'Sardo' },
  { id: 'SD', name: 'Sindhi' },
  { id: 'SE', name: 'Northern Sami' },
  { id: 'SG', name: 'Sango' },
  { id: 'SI', name: 'Singalese' },
  { id: 'SK', name: 'Slovacco' },
  { id: 'SL', name: 'Sloveno' },
  { id: 'SM', name: 'Samoano' },
  { id: 'SN', name: 'Shona' },
  { id: 'SO', name: 'Somalo' },
  { id: 'SQ', name: 'Albanese' },
  { id: 'SR', name: 'Serbo' },
  { id: 'SS', name: 'Swati' },
  { id: 'ST', name: 'Sotho del sud' },
  { id: 'SU', name: 'Sundanese' },
  { id: 'SV', name: 'Svedese' },
  { id: 'SW', name: 'Swahili' },
  { id: 'TA', name: 'Tamil' },
  { id: 'TE', name: 'Telugu' },
  { id: 'TG', name: 'Tagico' },
  { id: 'TH', name: 'Thailandese' },
  { id: 'TI', name: 'Tigrino' },
  { id: 'TK', name: 'Turkmeno' },
  { id: 'TL', name: 'Tagalog' },
  { id: 'TN', name: 'Tswano' },
  { id: 'TO', name: 'Tongano' },
  { id: 'TR', name: 'Turco' },
  { id: 'TS', name: 'Tsonga' },
  { id: 'TT', name: 'Tartaro' },
  { id: 'TW', name: 'Twi' },
  { id: 'TY', name: 'Tahitiano' },
  { id: 'UG', name: 'Uiguro' },
  { id: 'UK', name: 'Ucraino' },
  { id: 'UR', name: 'Urdu' },
  { id: 'UZ', name: 'Uzbeco' },
  { id: 'VE', name: 'Venda' },
  { id: 'VI', name: 'Vietnamita' },
  { id: 'VO', name: 'Volapük' },
  { id: 'WO', name: 'Wolof' },
  { id: 'XH', name: 'Xhosa' },
  { id: 'YI', name: 'Yiddish' },
  { id: 'YO', name: 'Yoruba' },
  { id: 'ZA', name: 'Zhuang' },
  { id: 'ZH', name: 'Chinese' },
  { id: 'ZU', name: 'Zulu' },
] as const;
export type Language = (typeof LANGUAGES)[number];

export const STATES = [
  {
    name: 'Afghanistan',
    provinces: [
      'Badakhshān',
      'Bādghīs',
      'Baghlān',
      'Balkh',
      'Bāmīān',
      'Farāh',
      'Fāryāb',
      'Ghaznī',
      'Ghowr',
      'Helmand',
      'Herāt',
      'Jowzjān',
      'Kabul (Kābol)',
      'Kandahār',
      'Kāpīsā',
      'Konar (Kunar)',
      'Kondoz (Kunduz)',
      'Laghmān',
      'Lowgar',
      'Nangrahār (Nangarhār)',
      'Nīmrūz',
      'Orūzgān (Urūzgā',
      'Paktīā',
      'Paktīkā',
      'Parwān',
      'Samangān',
      'Sar-e Pol',
      'Takhār',
      'Wardak (Wardag)',
      'Zābol (Zābul)',
    ],
  },
  {
    name: 'Albania',
    provinces: [
      'Berat',
      'Bulqizë',
      'Delvinë',
      'Devoll',
      'Dibër',
      'Durrës',
      'Elbasan',
      'Fier',
      'Gramsh',
      'Gjirokastër',
      'Has',
      'Kavajë',
      'Kolonjë',
      'Korcë',
      'Krujë',
      'Kucovë',
      'Kukës',
      'Laç',
      'Lezhë',
      'Librazhd',
      'Lushnjë',
      'Malësia e Madhe',
      'Mallakastër',
      'Mat',
      'Mirditë',
      'Peqin',
      'Përmet',
      'Pogradec',
      'Pukë',
      'Sarandë',
      'Skrapar',
      'Shkodër',
      'Tepelenë',
      'Tiranë',
      'Tropojë',
      'Vlorë',
    ],
  },
  {
    name: 'Algeria',
    provinces: [
      'Adrar',
      'Aïn Defla',
      'Aïn Témouchent',
      'Alger',
      'Batna',
      'Béchar',
      'Béjaïa',
      'Biskra',
      'Blida',
      'Bordj Bou Arréridj',
      'Bouira',
      'Boumerdès',
      'Chlef',
      'Constantine',
      'Djelfa',
      'El Bayadh',
      'El Oued',
      'El Tarf',
      'Ghardaïa',
      'Guelma',
      'Illizi',
      'Jijel',
      'Khenchela',
      'Laghouat',
      'Mascara',
      'Médéa',
      'Mila',
      'Mostaganem',
      'Msila',
      'Naama',
      'Oran',
      'Ouargla',
      'Oum el Bouaghi',
      'Relizane',
      'Saïda',
      'Sétif',
      'Sidi Bel Abbès',
      'Skikda',
      'Souk Ahras',
      'Tamanghasset',
      'Tébessa',
      'Tiaret',
      'Tindouf',
      'Tipaza',
      'Tissemsilt',
      'Tizi Ouzou',
      'Tlemcen',
    ],
  },
  {
    name: 'American Samoa',
    provinces: ['American Samoa'],
  },
  {
    name: 'Andorra',
    provinces: ['Andorra'],
  },
  {
    name: 'Angola',
    provinces: [
      'Bengo',
      'Benguela',
      'Bié',
      'Cabinda',
      'Cuando-Cubango',
      'Cuanza Norte',
      'Cuanza Sul',
      'Cunene',
      'Huambo',
      'Huíla',
      'Luanda',
      'Lunda Norte',
      'Lunda Sul',
      'Malange',
      'Moxico',
      'Namibe',
      'Uíge',
      'Zaïre',
    ],
  },
  {
    name: 'Anguilla',
    provinces: ['Anguilla'],
  },
  {
    name: 'Antarctica',
    provinces: ['Antarctica'],
  },
  {
    name: 'Antigua & Barbuda',
    provinces: ['Antigua & Barbuda'],
  },
  {
    name: 'Argentina',
    provinces: [
      'Capital federal',
      'Buenos Aires',
      'Catamarca',
      'Córdoba',
      'Corrientes',
      'Chaco',
      'Chubut',
      'Entre Ríos',
      'Formosa',
      'Jujuy',
      'La Pampa',
      'La Rioja',
      'Mendoza',
      'Misiones',
      'Neuquén',
      'Río Negro',
      'Salta',
      'San Juan',
      'San Luis',
      'Santa Cruz',
      'Santa Fe',
      'Santiago del Estero',
      'Tierra del Fuego',
      'Tucumán',
    ],
  },
  {
    name: 'Armenia',
    provinces: [
      'Erevan',
      'Aragacotn',
      'Ararat',
      'Armavir',
      "Geģark'unik'",
      "Kotayk'",
      'Loŕy',
      'Širak',
      "Syunik'",
      'Tavuš',
      'Vayoc Jor',
    ],
  },
  {
    name: 'Aruba',
    provinces: ['Aruba'],
  },
  {
    name: 'Australia',
    provinces: [
      'New South Wales',
      'Queensland',
      'South Australia',
      'Tasmania',
      'Victoria',
      'Western Australia',
      'Australian Capital Territory',
      'Northern Territory',
    ],
  },
  {
    name: 'Austria',
    provinces: [
      'Burgenland',
      'Kärnten',
      'Niederösterreich',
      'Oberösterreich',
      'Salzburg',
      'Steiermark',
      'Tirol',
      'Vorarlberg',
      'Wien',
    ],
  },
  {
    name: 'Azerbaijan',
    provinces: [
      'Naxçivan',
      'Äli Bayramli',
      'Baki',
      'Gäncä',
      'Länkäran',
      'Mingäçevir',
      'Naftalan',
      'Şäki',
      'Sumqayit',
      'Şuşa',
      'Xankändi',
      'Yevlax',
      'Abşeron',
      'Ağcabädi',
      'Ağdam',
      'Ağdas',
      'Ağstafa',
      'Ağsu',
      'Astara',
      'Babäk',
      'Balakän',
      'Bärdä',
      'Beyläqan',
      'Biläsuvar',
      'Cäbrayil',
      'Cälilabad',
      'Culfa',
      'Daşkäsän',
      'Däväçi',
      'Füzuli',
      'Gädäbäy',
      'Goranboy',
      'Göyçay',
      'Haciqabul',
      'Imişli',
      'Ismayilli',
      'Kälbäcär',
      'Kürdämir',
      'Laçin',
      'Länkäran',
      'Lerik',
      'Masalli',
      'Neftçala',
      'Oğuz',
      'Ordubad',
      'Qäbälä',
      'Qax',
      'Qazax',
      'Qobustan',
      'Quba',
      'Qubadlı',
      'Qusar',
      'Saatli',
      'Sabirabad',
      'Sädäräk',
      'Şahbuz',
      'Şäki',
      'Salyan',
      'Şamaxı',
      'Şämkir',
      'Samux',
      'Şärur',
      'Siyäzän',
      'Şuşa',
      'Tärtär',
      'Tovuz',
      'Ucar',
      'Xaçmaz',
      'Xanlar',
      'Xizi',
      'Xocalı',
      'Xocavänd',
      'Yardimli',
      'Yevlax',
      'Zängılan',
      'Zaqatala',
      'Zärdab',
    ],
  },
  {
    name: 'Bahamas',
    provinces: [
      'Acklins and Crooked Islands',
      'Bimini',
      'Cat Island',
      'Exuma',
      'Freeport',
      'Fresh Creek',
      "Governor's Harbour",
      'Green Turtle Cay',
      'Harbour Island',
      'High Rock',
      'Inagua',
      'Kemps Bay',
      'Long Island',
      'Marsh Harbour',
      'Mayaguana',
      'New Providence',
      'Nicholls Town and Berry Islands',
      'Ragged Island',
      'Rock Sound',
      'Sandy Point',
      'San Salvador and Rum Cay',
    ],
  },
  {
    name: 'Bahrain',
    provinces: [
      'Al Ḩadd',
      'Al Manāmah',
      'Al Minţaqah al Gharbīyah',
      'Al Minţaqah al Wusţa',
      'Al Minţaqah ash Shamālīyah',
      'Al Muḩarraq',
      'Ar Rifā‘',
      'Jidd Ḩafş',
      'Madīnat Ḩamad',
      'Madīnat ‘Īsá',
      'Minţaqat Juzur Ḩawār',
      'Sitrah',
    ],
  },
  {
    name: 'Bangladesh',
    provinces: [
      'Barisal bibhag',
      'Barisal anchal',
      'Patuakhali anchal',
      'Chittagong bibhag',
      'Bandarban anchal',
      'Chittagong anchal',
      'Chittagong Hill Tracts',
      'Comilla anchal',
      'Noakhali anchal',
      'Sylhet anchal',
      'Dhaka bibhag',
      'Dhaka anchal',
      'Faridpur anchal',
      'Jamalpur anchal',
      'Mymensingh anchal',
      'Tangail anchal',
      'Khulna bibhag',
      'Jessore anchal',
      'Khulna anchal',
      'Khustia anchal',
      'Rajshahi bibhag',
      'Bogra anchal',
      'Dinajpur anchal',
      'Pabna anchal',
      'Rajshahi anchal',
      'Rangpur anchal',
    ],
  },
  {
    name: 'Barbados',
    provinces: ['Barbados'],
  },
  {
    name: 'Belarus',
    provinces: [
      "Brestskaya voblasts'",
      "Homyel'skaya voblasts’",
      "Hrodnenskaya voblasts'",
      "Mahilyowskaya voblasts'",
      "Minskaya voblasts'",
      "Vitsyebskaya voblasts'",
    ],
  },
  {
    name: 'Belgium',
    provinces: [
      'Bruxelles-Capitale, Region de (fr), Brussels Hoofdstedelijk Gewest (nl)',
      'Vlaamse Gewest (nl)',
      'Antwerpen (nl)',
      'Limburg (nl)',
      'Oost-Vlaanderen (nl)',
      'Vlaams Brabant (nl)',
      'West-Vlaanderen (nl)',
      'Wallonne, Region (fr)',
      'Brabant Wallon (fr)',
      'Hainaut (fr)',
      'Liège (fr)',
      'Luxembourg (fr)',
      'Namur (fr)',
    ],
  },
  {
    name: 'Belize',
    provinces: [
      'Belize',
      'Cayo',
      'Corozal',
      'Orange Walk',
      'Stann Creek',
      'Toledo',
    ],
  },
  {
    name: 'Benin',
    provinces: ['Atakora', 'Atlantique', 'Borgou', 'Mono', 'Ouémé', 'Zou'],
  },
  {
    name: 'Bermuda',
    provinces: ['Bermuda'],
  },
  {
    name: 'Bhutan',
    provinces: [
      'Bumthang',
      'Chhukha',
      'Dagana',
      'Gasa',
      'Ha',
      'Lhuentse',
      'Monggar',
      'Paro',
      'Pemagatshel',
      'Punakha',
      'Samdrup Jongkha',
      'Samtse',
      'Sarpang',
      'Thimphu',
      'Trashigang',
      'Trashi Yangtse',
      'Trongsa',
      'Tsirang',
      'Wangdue Phodrang',
      'Zhemgang',
    ],
  },
  {
    name: 'Bolivia',
    provinces: [
      'Cochabamba',
      'Chuquisaca',
      'El Beni',
      'La Paz',
      'Oruro',
      'Pando',
      'Potosi',
      'Santa Cruz',
      'Tarija',
    ],
  },
  {
    name: 'Bosnia & Herzegovina',
    provinces: ['Federacija Bosna i Hercegovina', 'Republika Srpska'],
  },
  {
    name: 'Botswana',
    provinces: [
      'Central [Serowe-Palapye]',
      'Chobe',
      'Ghanzi',
      'Kgalagadi',
      'Kgatleng',
      'Kweneng',
      'Ngamiland [North-West]',
      'North-East',
      'South-East',
      'Southern [Ngwaketse]',
    ],
  },
  {
    name: 'Bouvet Island',
    provinces: ['Bouvet Island'],
  },
  {
    name: 'Brazil',
    provinces: [
      'Distrito Federal',
      'Acre',
      'Alagoas',
      'Amapá',
      'Amazonas',
      'Bahia',
      'Ceará',
      'Espírito Santo',
      'Goiás',
      'Maranhāo',
      'Mato Grosso',
      'Mato Grosso do Sul',
      'Minas Gerais',
      'Pará',
      'Paraíba',
      'Paraná',
      'Pernambuco',
      'Piauí',
      'Rio de Janeiro',
      'Rio Grande do Norte',
      'Rio Grande do Sul',
      'Rondônia',
      'Roraima',
      'Santa Catarina',
      'São Paulo',
      'Sergipe',
      'Tocantins',
    ],
  },
  {
    name: 'British Indian Ocean Territory',
    provinces: ['British Indian Ocean Territory'],
  },
  {
    name: 'Brunei Darussalam',
    provinces: ['Belait', 'Brunei-Muara', 'Temburong', 'Tutong'],
  },
  {
    name: 'Bulgaria',
    provinces: [
      'Burgas',
      'Haskovo',
      'Loveč',
      'Montana',
      'Plovdiv',
      'Ruse',
      'Sofija',
      'Sofija-Grad',
      'Varna',
    ],
  },
  {
    name: 'Burkina Faso',
    provinces: [
      'Balé',
      'Bam',
      'Banwa',
      'Bazèga',
      'Bougouriba',
      'Boulgou',
      'Boulkiemdé',
      'Comoé',
      'Ganzourgou',
      'Gnagna',
      'Gourma',
      'Houet',
      'Ioba',
      'Kadiogo',
      'Kénédougou',
      'Komondjari',
      'Kompienga',
      'Kossi',
      'Koulpélogo',
      'Kouritenga',
      'Kourwéogo',
      'Léraba',
      'Loroum',
      'Mouhoun',
      'Nahouri',
      'Namentenga',
      'Nayala',
      'Noumbiel',
      'Oubritenga',
      'Oudalan',
      'Passoré',
      'Poni',
      'Sanguié',
      'Sanmatenga',
      'Séno',
      'Sissili',
      'Soum',
      'Sourou',
      'Tapoa',
      'Tui',
      'Yagha',
      'Yatenga',
      'Ziro',
      'Zondoma',
      'Zoundwéogo',
    ],
  },
  {
    name: 'Burundi',
    provinces: [
      'Bubanza',
      'Bujumbura',
      'Bururi',
      'Cankuzo',
      'Cibitoke',
      'Gitega',
      'Karuzi',
      'Kayanza',
      'Kirundo',
      'Makamba',
      'Muramvya',
      'Muyinga',
      'Ngozi',
      'Rutana',
      'Ruyigi',
    ],
  },
  {
    name: 'Cambodia',
    provinces: [
      'Krong Kaeb [Krŏng Kêb]',
      'Krong Preah Sihanouk [Krŏng Preăh Sihanouk]',
      'Phnom Penh [Phnum Pénh]',
      'Baat Dambang [Bătdâmbâng]',
      'Banteay Mean Chey [Bântéay Méanchey]',
      'Kampong Chaam [Kâmpóng Cham]',
      'Kampong Chhnang [Kâmpóng Chhnăng]',
      'Kampong Spueu [Kâmpóng Spœ]',
      'Kampong Thum [Kâmpóng Thum]',
      'Kampot [Kâmpôt]',
      'Kandaal [Kândal]',
      'Kracheh [Krâchéh]',
      'Mond01 Kiri [Môndól Kiri]',
      'Otdar Mean Chey [Ŏtdâr Méanchey]',
      'Pousaat [Poŭthĭsăt]',
      'Preah Vihear [Preăh Vihéar]',
      'Prey Veaeng [Prey Vêng]',
      'Rotanak Kiri [Rôtânôkiri]',
      'Siem Reab [Siĕmréab]',
      'Stueng Traeng [Stœng Trêng]',
      'Svaay Rieng [Svay Riĕng]',
      'Taakaev [Takêv]',
    ],
  },
  {
    name: 'Cameroon',
    provinces: [
      'Adamaoua',
      'Centre',
      'Est',
      'Far North',
      'Littoral',
      'North',
      'North-West',
      'South',
      'South-West',
      'West',
    ],
  },
  {
    name: 'Canada',
    provinces: [
      'Alberta',
      'British Columbia (Colombie-Britannique)',
      'Manitoba',
      'New Brunswick (Nouveau-Brunswick)',
      'Newfoundland and Labrador (Terre-Neuve)',
      'Nova Scotia (Nouvelle-Écosse)',
      'Ontario',
      'Prince Edward Island (Île-du-Prince-Édouard)',
      'Quebec (Québec)',
      'Saskatchewan',
      'Northwest Territories (Territoires du Nord-Ouest)',
      'Nunavut',
      'Yukon Territory (Teritoire du Yukon)',
    ],
  },
  {
    name: 'Cape Verde',
    provinces: [
      'Ilhas de Barlavento',
      'Boa Vista',
      'Paul',
      'Porto Novo',
      'Ribeira Grande',
      'Sal',
      'Sāo Nicolau',
      'Sāo Vicente',
      'Ilhas de Sotavento',
      'Brava',
      'Fogo',
      'Maio',
      'Praia',
      'Santa Catarina',
      'Santa Cruz',
      'Tarrafal',
    ],
  },
  {
    name: 'Cayman Islands',
    provinces: ['Cayman Islands'],
  },
  {
    name: 'Central African Republic',
    provinces: [
      'Bangui',
      'Bamingui-Bangoran',
      'Basse-Kotto',
      'Haute-Kotto',
      'Haut-Mbomou',
      'Kémo',
      'Lobaye',
      'Mambéré-Kadéï',
      'Mbomou',
      'Nana-Grébizi',
      'Nana-Mambéré',
      'Ombella-Mpoko',
      'Ouaka',
      'Ouham',
      'Ouham-Pendé',
      'Sangha-Mbaéré',
      'Vakaga',
    ],
  },
  {
    name: 'Chad',
    provinces: [
      'Batha',
      'Biltine',
      'Borkou-Ennedi-Tibesti',
      'Chari-Baguirmi',
      'Guéra',
      'Kanem',
      'Lac',
      'Logone-Occidental',
      'Logone-Oriental',
      'Mayo-Kébbi',
      'Moyen-Chari',
      'Ouaddaï',
      'Salamat',
      'Tandjilé',
    ],
  },
  {
    name: 'Chile',
    provinces: [
      'Aisén del General Carlos Ibáñiez del Campo',
      'Antofagasta',
      'Araucanía',
      'Atacama',
      'Bío-Bío',
      'Coquimbo',
      "Libertador General Bernardo O'Higgins",
      'Los Lagos',
      'Magallanes',
      'Maule',
      'Regíon Metropolitana de Santiago',
      'Tarapacá',
      'Valparaiso',
    ],
  },
  {
    name: 'China',
    provinces: [
      'Beijing',
      'Chongqing',
      'Shanghai',
      'Tianjin',
      'Anhui',
      'Fujian',
      'Gansu',
      'Guangdong',
      'Guizhou',
      'Hainan',
      'Hebei',
      'Heilongjiang',
      'Henan',
      'Hubei',
      'Hunan',
      'Jiangsu',
      'Jiangxi',
      'Jilin',
      'Liaoning',
      'Qinghai',
      'Shaanxi',
      'Shandong',
      'Shanxi',
      'Sichuan',
      'Taiwan',
      'Yunnan',
      'Zhejiang',
      'Guangxi',
      'Nei Monggol',
      'Ningxia',
      'Xinjiang',
      'Xizang',
      'Hong Kong',
    ],
  },
  {
    name: 'Christmas Island',
    provinces: ['Christmas Island'],
  },
  {
    name: 'Cocos (Keeling) Islands',
    provinces: ['Cocos (Keeling) Islands'],
  },
  {
    name: 'Colombia',
    provinces: [
      'Distrito Capital de Santa Fe de Bogota',
      'Amazonas',
      'Antioguia',
      'Arauca',
      'Atlántico',
      'Bolívar',
      'Boyacá',
      'Caldas',
      'Caquetá',
      'Casanare',
      'Cauca',
      'Cesar',
      'Córdoba',
      'Cundinamarca',
      'Chocó',
      'Guainía',
      'Guaviare',
      'Huila',
      'La Guajira',
      'Magdalena',
      'Meta',
      'Nariño',
      'Norte de Santander',
      'Putumayo',
      'Quindío',
      'Risaralda',
      'San Andrés, Providencia y Santa Catalina',
      'Santander',
      'Sucre',
      'Tolima',
      'Valle del Cauca',
      'Vaupés',
      'Vichada',
    ],
  },
  {
    name: 'Comoros',
    provinces: [
      'Anjouan (Ndzouani)',
      'Grande Comore (Ngazidja)',
      'Mohéli (Moili)',
    ],
  },
  {
    name: 'Congo',
    provinces: [
      'Brazzaville',
      'Bouenza',
      'Cuvette',
      'Cuvette-Ouest',
      'Kouilou',
      'Lékoumou',
      'Likouala',
      'Niari',
      'Plateaux',
      'Pool',
      'Sangha',
    ],
  },
  {
    name: 'Zaire',
    provinces: [
      'Kinshasa',
      'Bandundu',
      'Bas-Congo',
      'Équateur',
      'Haut-Congo',
      'Kasai-Occidental',
      'Kasai-Oriental',
      'Katanga',
      'Maniema',
      'Nord-Kivu',
      'Sud-Kivu',
    ],
  },
  {
    name: 'Cook Islands',
    provinces: ['Cook Islands'],
  },
  {
    name: 'Costa Rica',
    provinces: [
      'Alajuela',
      'Cartago',
      'Guanacaste',
      'Heredia',
      'Limón',
      'Puntarenas',
      'San José',
    ],
  },
  {
    name: "Cote D'ivoire (Ivory Coast)",
    provinces: [
      '18 Montagnes (Région des)',
      "Agnébi (Région de l')",
      'Bas-Sassandra (Région du)',
      'Denguélé (Région du)',
      'Haut-Sassandra (Région du)',
      'Lacs (Région des)',
      'Lagunes (Région des)',
      'Marahoué (Région de la)',
      'Moyen-Comoé (Région du)',
      'Nzi-Comoé (Région)',
      'Savanes (Région des)',
      'Sud-Bandama (Région du)',
      'Sud-Comoé (Région du)',
      'Vallée du Bandama (Région de la)',
      'Worodougou (Région du)',
      'Zanzan (Région du)',
    ],
  },
  {
    name: 'Croatia (Hrvatska)',
    provinces: [
      'Bjelovarsko-bilogorska županija',
      'Brodsko-posavska županija',
      'Dubrovačko-neretvanska županija',
      'Istarska županija',
      'Karlovačka županija',
      'Koprivničkco-križevačka županija',
      'Krapinsko-zagorska županija',
      'Ličko-senjska županija',
      'Medjimurska županija',
      'Osječko-baranjska županija',
      'Požeško-slavonska županija',
      'Primorsko-goranska županija',
      'Sisaško-moslavačka županija',
      'Splitsko-dalmatinska županija',
      'Šibensko-kninska županija',
      'Varaždinska županija',
      'Virovitičko-podravska županija',
      'Vukovarsko-srijemska županija',
      'Zadarska županija',
      'Zagrebačka županija',
    ],
  },
  {
    name: 'Cuba',
    provinces: [
      'Camagüey',
      'Ciudad de La Habana',
      'Granma',
      'Guantánamo',
      'Holguín',
      'La Habana',
      'Las Tunas',
      'Matanzas',
      'Pinar del Río',
      'Sancti Spíritus',
      'Santiago de Cuba',
      'Villa Clara',
      'Isla de la Juventud',
    ],
  },
  {
    name: 'Cyprus',
    provinces: [
      'Ammochostos (Mağusa)',
      'Keryneia (Girne)',
      'Larnaka',
      'Lefkosia (Lefkoşa)',
      'Lemesos (Leymosun)',
      'Pafos (Baf)',
    ],
  },
  {
    name: 'Czech Republic',
    provinces: [
      'Praha',
      'Jihočeský kraj',
      'Jihomoravský kraj',
      'Severočeský kraj',
      'Severomoravský kraj',
      'Středočeský kraj',
      'Východočeský kraj',
      'Západočeský kraj',
    ],
  },
  {
    name: 'Denmark',
    provinces: [
      'Frederiksberg',
      'Kǿbenhavn',
      'Bornholm',
      'Frederiksborg',
      'Fyn',
      'Kǿbenhavn',
      'Nordjylland',
      'Ribe',
      'Ringkǿbing',
      'Roskilde',
      'Storstrǿm',
      'Sǿnderjylland',
      'Vejle',
      'Vestsjælland',
      'Viborg',
      'Århus',
    ],
  },
  {
    name: 'Djibouti',
    provinces: ['Ali Sabieh', 'Dikhil', 'Djibouti', 'Obock', 'Tadjoura'],
  },
  {
    name: 'Dominica',
    provinces: ['Dominica'],
  },
  {
    name: 'Dominican Republic',
    provinces: [
      'Distrito National (Santo Domingo)',
      'Azua',
      'Bahoruco',
      'Barahona',
      'Dajabón',
      'Duarte',
      'El Seibo',
      'La Estrelleta [Elías Piña]',
      'Hato Mayor',
      'Independencia',
      'La Altagracia',
      'La Romana',
      'La Vega',
      'María Trinidad Sánchez',
      'Monseñor Nouel',
      'Monte Cristi',
      'Monte Plata',
      'Pedernales',
      'Peravia',
      'Puerto Plata',
      'Salcedo',
      'Samaná',
      'Sanchez Ramírez',
      'San Cristóbal',
      'San Juan',
      'San Pedro de Macorís',
      'Santiago',
      'Santiago Rodríguez',
      'Valverde',
    ],
  },
  {
    name: 'East Timor',
    provinces: ['East Timor'],
  },
  {
    name: 'Ecuador',
    provinces: [
      'Azuay',
      'Bolívar',
      'Cañar',
      'Carchi',
      'Cotopaxi',
      'Chimborazo',
      'El Oro',
      'Esmeraldas',
      'Galápagos',
      'Guayas',
      'Imbabura',
      'Loja',
      'Los Ríos',
      'Manabí',
      'Morona-Santiago',
      'Napo',
      'Pastaza',
      'Pichincha',
      'Sucumbíos',
      'Tungurahua',
      'Zarnora-Chinchipe',
    ],
  },
  {
    name: 'Egypt',
    provinces: [
      'Ad Daqahlīyah',
      'Al Baḩr al Aḩmar',
      'Al Buḩayrah',
      'Al Fayyūm',
      'Al Gharbīyah',
      'Al Iskandarīyah',
      'Al Ismā‘īlīyah',
      'Al Jīzah',
      'Al Minūfīyah',
      'Al Minyā',
      'Al Qāhirah',
      'Al Qalyūbīyah',
      'Al Wādī al Jadīd',
      'Ash Sharqīyah',
      'As Suways',
      'Aswān',
      'Asyūţ',
      'Banī Suwayf',
      'Būr Sa‘īd',
      'Dumyāţ',
      "Janūb Sīnā'",
      'Kafr ash Shaykh',
      'Maţrūḩ',
      'Qinā',
      "Shamāl Sīnā'",
      'Sūhāj',
    ],
  },
  {
    name: 'El Salvador',
    provinces: [
      'Ahuachapán',
      'Cabañas',
      'Cuscatlán',
      'Chalatenango',
      'La Libertad',
      'La Paz',
      'La Unión',
      'Morazán',
      'San Miguel',
      'San Salvador',
      'Santa Ana',
      'San Vicente',
      'Sonsonate',
      'Usulután',
    ],
  },
  {
    name: 'Equatorial Guinea',
    provinces: [
      'Región Continental',
      'Centro Sur',
      'Kie-Ntem',
      'Litoral',
      'Wele-Nzás',
      'Región Insular',
      'Annobón',
      'Bioko Norte',
      'Bioko Sur',
    ],
  },
  {
    name: 'Eritrea',
    provinces: [
      'Akele Guzai [Akalä Guzay]',
      'Asmara [Asmära]',
      'Barka',
      'Denkalia [Dänkali]',
      'Gash-Setit [Gaš enna Sätit]',
      'Hamasien [Hamasén]',
      'Sahel',
      'Semhar [Sämhar]',
      'Senhit [Sänhet]',
      'Seraye [Särayé]',
    ],
  },
  {
    name: 'Estonia',
    provinces: [
      'Harjumaa',
      'Hiiumaa',
      'Ida-Virumaa',
      'Jōgevamaa',
      'Järvamaa',
      'Läänemaa',
      'Lääne-Virumaa',
      'Pōlvamaa',
      'Pärnumaa',
      'Raplamaa',
      'Saaremaa',
      'Tartumaa',
      'Valgamaa',
      'Viljandimaa',
      'Vōrumaa',
    ],
  },
  {
    name: 'Ethiopia',
    provinces: [
      'Addis Ababa [Addis Abeba]',
      'Afar',
      'Amara [Amhara]',
      'Benshangul-Gumaz [Bénishangul]',
      'Gambela Peoples [Gambéla]',
      'Harari People [Harer]',
      'Oromia [Oromo]',
      'Somali',
      'Southern Nations, Nationalities and Peoples',
      'Tigrai [Tegré]',
    ],
  },
  {
    name: 'Falkland Islands (Malvinas)',
    provinces: ['Falkland Islands (Malvinas)'],
  },
  {
    name: 'Faroe Islands',
    provinces: ['Faroe Islands'],
  },
  {
    name: 'Fiji',
    provinces: ['Central', 'Eastern', 'Northern', 'Western', 'Rotuma'],
  },
  {
    name: 'Finland',
    provinces: [
      'Ahvenanmaan lääni',
      'Etelä-Suomen lääni',
      'Itä-Suomen lääni',
      'Lapin lääni',
      'Länsi-Suomen lääni',
      'Oulun lääni',
    ],
  },
  {
    name: 'France',
    provinces: [
      'Alsace',
      'Bas-Rhin',
      'Haut-Rhin',
      'Aquitaine',
      'Deux-Sèvres',
      'Dordogne',
      'Gironde',
      'Landes',
      'Lot-et-Garonne',
      'Pyrénées-Atlantiques',
      'Auvergne',
      'Allier',
      'Cantal',
      'Haute-Loire',
      'Puy-de-Dôme',
      'Basse-Normandie',
      'Calvados',
      'Manche',
      'Orne',
      'Bourgogne',
      "Côte-d'Or",
      'Nièvre',
      'Saône-et-Loire',
      'Yonne',
      'Bretagne',
      "Cotes-d'Armor",
      'Finistère',
      'Ille-et-Vilaine',
      'Morbihan',
      'Centre',
      'Cher',
      'Eure-et-Loir',
      'Indre',
      'Indre-et-Loire',
      'Loir-et-Cher',
      'Loiret',
      'Champagne-Ardenne',
      'Ardennes',
      'Aube',
      'Haute-Marne',
      'Marne',
      'Corse',
      'Corse-du-Sud',
      'Haute-Corse',
      'Franche-Comté',
      'Doubs',
      'Haute-Saône',
      'Jura',
      'Territoire de Belfort',
      'Haute-Normandie',
      'Eure',
      'Seine-Maritime',
      'Île-de-France',
      'Essonne',
      'Hauts-de-Seine',
      'Paris',
      'Seine-et-Marne',
      'Seine-Saint-Denis',
      'Val-de-Marne',
      "Val-d'Oise",
      'Yvelines',
      'Languedoc-Roussillon',
      'Aude',
      'Gard',
      'Hérault',
      'Lozère',
      'Pyrénées-Orientales',
      'Limousin',
      'Corrèze',
      'Creuse',
      'Haute-Vienne',
      'Lorraine',
      'Meurthe-et-Moselle',
      'Meuse',
      'Moselle',
      'Vosges',
      'Midi-Pyrénées',
      'Ariège',
      'Aveyron',
      'Gers',
      'Haute-Garonne',
      'Hautes-Pyrénées',
      'Lot',
      'Tarn',
      'Tarn-et-Garonne',
      'Nord-Pas-de-Calais',
      'Nord',
      'Pas-de-Calais',
      'Pays de la Loire',
      'Loire-Atlantique',
      'Maine-et-Loire',
      'Mayenne',
      'Sarthe',
      'Vendée',
      'Picardie',
      'Aisne',
      'Oise',
      'Somme',
      'Poitou-Charentes',
      'Charente',
      'Charente-Maritime',
      'Vienne',
      "Provence-Alpes-Côte d'Azur",
      'Alpes-de-Haute-Provence',
      'Alpes-Maritimes',
      'Bauches-du-Rhône',
      'Hautes-Alpes',
      'Var',
      'Vaucluse',
      'Rhône-Alpes',
      'Ain',
      'Ardèche',
      'Drôme',
      'Haute-Savoie',
      'Isère',
      'Loire',
      'Rhône',
      'Savoie',
      'Guadeloupe',
      'Guyane (francaise)',
      'Martinique',
      'Réunion',
      'Mayotte',
      'Saint-Pierre-et-Miquelon',
      'Nouvelle-Calédonie',
      'Polynésie française',
      'Terres Australes',
      'Wallis et Futuna',
    ],
  },
  {
    name: 'French Guiana',
    provinces: ['French Guiana'],
  },
  {
    name: 'French Polynesia',
    provinces: ['French Polynesia'],
  },
  {
    name: 'French Southern Territories',
    provinces: ['French Southern Territories'],
  },
  {
    name: 'Gabon',
    provinces: [
      'Estuaire',
      'Haut-Ogooué',
      'Moyen-Ogooué',
      'Ngounié',
      'Nyanga',
      'Ogooué-Ivindo',
      'Ogooué-Lolo',
      'Ogooué-Maritime',
      'Woleu-Ntem',
    ],
  },
  {
    name: 'Gambia',
    provinces: [
      'Banjul',
      'Lower River',
      'MacCarthy Island',
      'North Bank',
      'Upper River',
      'Western',
    ],
  },
  {
    name: 'Georgia',
    provinces: [
      "Ap'khazet'is Avtonomiuri Respublika [Abkhazia]",
      'Acharis Avtonomiuri Respublika [Ajaria]',
      "Bat'umi",
      "Chiat'ura",
      'Gagra',
      'Gori',
      "K'ut'aisi",
      "P'ot'i",
      "Rust'avi",
      'Sokhumi',
      "T'bilisi",
      'Tqibuli',
      "Tqvarch'eli",
      'Tsqalmbo',
      'Zugdidi',
      'Abashis Raioni',
      'Adigenis Raioni',
      'Akhalgoris Raioni',
      "Akhalk'alak'is Raioni",
      "Akhalts'ikhis Raioni",
      'Akhmetis Raioni',
      'Ambrolauris Raioni',
      'Aspindzis Raioni',
      "Baghdat'is Raioni",
      'Bolnisis Raioni',
      'Borjomis Raioni',
      "Ch'khorotsqus Raioni",
      "Ch'okhatauris Raioni",
      "Dedop'listsqaros Raioni",
      'Dmanisis Raioni',
      "Dushet'is Raioni",
      'Galis Raioni',
      'Gardabnis Raioni',
      'Goris Raioni',
      "Gudaut'is Raioni",
      "Gulrip'shis Raioni",
      'Gurjaanis Raioni',
      'Javis Raioni',
      "K'arelis Raioni",
      'Kaspis Raioni',
      "K'edis Raioni",
      'Kharagaulis Raioni',
      'Khashuris Raioni',
      "Khelvach'auris Raioni",
      'Khobis Raioni',
      'Khonis Raioni',
      'Khulos Raioni',
      "K'obuletis Raioni",
      'Lagodekhis Raioni',
      "Lanch'khut'is Raioni",
      'Lentekhis Raioni',
      'Marneulis Raioni',
      'Martvilis Raioni',
      'Mestiis Raioni',
      "Mts'khet'is Raioni",
      'Ninotsmindis Raioni',
      "Och'amch'iris Raioni",
      'Onis Raioni',
      "Ozurget'is Raioni",
      'Qazbegis Raioni',
      'Qvarlis Raioni',
      "Sach'kheris Raioni",
      'Sagarejos Raioni',
      'Samtrediis Raioni',
      'Senakis Raioni',
      'Shuakhevis Raioni',
      'Sighnaghis Raioni',
      'Sokhumis Raioni',
      "T'elavis Raioni",
      "T'erjolis Raioni",
      "T'et'ritsqaros Raioni",
      "T'ianet'is Raioni",
      "Ts'ageris Raioni",
      'Tsalenjikhis Raioni',
      'Tsalkis Raioni',
      'Vanis Raioni',
      "Zestap'onis Raioni",
      'Zugdidis Raioni',
    ],
  },
  {
    name: 'Germany',
    provinces: [
      'Baden-Württemberg',
      'Bayern',
      'Berlin',
      'Brandenburg',
      'Bremen',
      'Hamburg',
      'Hessen',
      'Mecklenburg-Vorpommern',
      'Niedersachsen',
      'Nordrhein-Westfalen',
      'Rheinland-Pfalz',
      'Saarland',
      'Sachsen',
      'Sachsen-Anhalt',
      'Schleswig-Holstein',
      'Thüringen',
    ],
  },
  {
    name: 'Ghana',
    provinces: [
      'Ashanti',
      'Brong-Ahafo',
      'Central',
      'Eastern',
      'Greater Accra',
      'Northern',
      'Upper East',
      'Upper West',
      'Volta',
      'Western',
    ],
  },
  {
    name: 'Gibraltar',
    provinces: ['Gibraltar'],
  },
  {
    name: 'United Kingdom',
    provinces: [
      'Channel Islands',
      'Guernsey [Guernesey]',
      'Jersey',
      'England',
      'Barking and Dagenham',
      'Barnet',
      'Barnsley',
      'Bath and North East Somerset',
      'Bedfordshire',
      'Bexley',
      'Birmingham (City of)',
      'Blackburn with Darwen',
      'Blackpool',
      'Bolton',
      'Bournemouth',
      'Bracknell Forest',
      'Bradford (City of)',
      'Brent',
      'Brighton and Hove',
      'Bristol, City of',
      'Bromley',
      'Buckinghamshire',
      'Bury',
      'Calderdale',
      'Cambridgeshire',
      'Camden',
      'Cheshire',
      'Cornwall',
      'Coventry (City of)',
      'Croydon',
      'Cumbria',
      'Darlington',
      'Derby (City of)',
      'Derbyshire',
      'Devon',
      'Doncaster',
      'Dorset',
      'Dudley',
      'Durharn',
      'Ealing',
      'East Riding of Yorkshire',
      'East Sussex',
      'Enfield',
      'Essex',
      'Gateshead',
      'Gloucestershire',
      'Greenwich',
      'Hackney',
      'Haiton',
      'Hammersmith and Fulham',
      'Hampshire',
      'Haringey',
      'Harrow',
      'Hartlepool',
      'Havering',
      'Herefordshire, County of',
      'Hertfordshire',
      'Hillingdon',
      'Hounslow',
      'Isle of Wight',
      'Isles of Scilly',
      'Islington',
      'Kensington and Chelsea',
      'Kent',
      'Kingston upon Hull, City of',
      'Kingston upon Thames',
      'Kirklees',
      'Knowsley',
      'Lambeth',
      'Lancashire',
      'Leeds (City of)',
      'Leitester (City of)',
      'Leicestershire',
      'Lewisham',
      'Lincolnshire',
      'Liverpool (City of)',
      'London, City of',
      'Luton',
      'Manchester (City of)',
      'Medway',
      'Merton',
      'Middlesbrough',
      'Milton Keynes',
      'Newcastle upon Tyne (City of)',
      'Newham',
      'Norfolk',
      'North East Lincolnshire',
      'North Lincolnshire',
      'North Somerset',
      'North Tyneside',
      'North Yorkshire',
      'Northamptonshire',
      'Northumberland',
      'Nottingham (City of)',
      'Nottinghamshire',
      'Oldham',
      'Oxfordshire',
      'Peterborough',
      'Plymouth (City of)',
      'Poole',
      'Portsmouth (City of)',
      'Reading',
      'Redbridge',
      'Redcar and Cleveland',
      'Richmond upon Thames',
      'Rochdale',
      'Rotherharn',
      'Rutland',
      'St. Helens',
      'Salford (City of)',
      'Sandweil',
      'Sefton',
      'Sheffield (City of)',
      'Shropshire',
      'Slough',
      'Solihull',
      'Somerset',
      'South Gloucestershire',
      'South Tyneside',
      'Southampton (City of)',
      'Southend-on-Sea',
      'Southwark',
      'Staffordshire',
      'Stockport',
      'Stockton-On-Tees',
      'Stoke-on-Trent (City of)',
      'Suffolk',
      'Sunderland (City of)',
      'Surrey',
      'Sutton',
      'Swindon',
      'Tameside',
      'Telford and Wrekin',
      'Thurrock',
      'Torbay',
      'Tower Hamlets',
      'Trafford',
      'Wakefield (City of)',
      'Walsall',
      'Waltham Forest',
      'Wandsworth',
      'Warrington',
      'Warwickshire',
      'West Berkshire',
      'West Sussex',
      'Westminster (City of)',
      'Wigan',
      'Wiltshire',
      'Windsor and Maidenhead',
      'Wirral',
      'Wokingham',
      'Wolverhampton',
      'Worcestershire',
      'York (City of)',
      'Isle of Man',
      'Northern Ireland',
      'Antrim',
      'Ards',
      'Armagh',
      'Ballymena',
      'Ballymoney',
      'Banbridge',
      'Belfast (City of)',
      'Carrickfergus',
      'Castlereagh',
      'Coleraine',
      'Cookstown',
      'Craigavon',
      'Derry (City of)',
      'Down',
      'Dungannon',
      'Fermanagh',
      'Larne',
      'Limavady',
      'Lisburn',
      'Magherafelt',
      'Moyle',
      'Newry and Mourne',
      'Newtownabbey',
      'North Down',
      'Omagh',
      'Strabane',
      'Scotland',
      'Aberdeen City',
      'Aberdeenshire',
      'Angus',
      'Argyll and Bute',
      'Clackmannanshire',
      'Dumfries and Galloway',
      'Dundee City',
      'East Ayrshire',
      'East Dunbartonshire',
      'East Lothian',
      'East Renfrewshire',
      'Edinburgh, City of',
      'Eilean Siar',
      'Falkirk',
      'Fife',
      'Glasgow City',
      'Highland',
      'Inverclyde',
      'Midlothian',
      'Moray',
      'North Ayrshire',
      'North Lanarkshire',
      'Orkney Islands',
      'Perth and Kinross',
      'Renfrewshire',
      'Scottish Borders, The',
      'Shetland Islands',
      'South Ayrshire',
      'South Lanarkshire',
      'Stirling',
      'West Dunbartonshire',
      'West Lothian',
      'Wales [Cymru]',
      'Blaenau Gwent',
      'Bridgend [Pen-y-bont ar Ogwr GB-POG]',
      'Caerphilly [Caerffili GB-CAF]',
      'Cardiff (City of) [Caerdydd GB-CRD]',
      'Carmarthenshire [Sir Gaerfyrddin GB-GFY]',
      'Ceredigion [Sir Ceredigion]',
      'Conwy',
      'Denbighshire [Sir Ddinbych GB-DDB]',
      'Flintshire [Sir y Fflint GB-FFL]',
      'Gwynedd',
      'Isle of Anglesey [Sir Ynys Man GB-YNM]',
      'Merthyr Tydfil [Merthyr Tudful GB-MTU]',
      'Monmouthshire [Sir Fynwy GB-FYN]',
      'Neath Port Talbot [Castell-nedd Port Talbot GB-CTL]',
      'Newport [Casnewydd GB-CNW]',
      'Pembrokeshire [Sir Benfro CB-BNF]',
      'Powys',
      'Rhondda, Cynon, Taff [Rhondda, Cynon, Taf]',
      'Swansea (City of) [Abertawe GB-ATA]',
      'Torfaen [Tor-faen]',
      'Vale of Glamorgan, The [Bro Morgannwg GB-BMG]',
      'Wrexham [Wrecsam GB-WRC]',
    ],
  },
  {
    name: 'Greece',
    provinces: [
      'Anatoliki Makedonia kai Thraki',
      'Drama',
      'Evros',
      'Kavalla',
      'Rodopi',
      'Xanthi',
      'Attiki',
      'Attiki',
      'Dytiki Ellada',
      'Achaïa',
      'Aitolia-Akarnania',
      'Ileia',
      'Dytiki Makedonia',
      'Florina',
      'Grevena',
      'Kastoria',
      'Kozani',
      'Ionioi Nisoi',
      'Kefallinia',
      'Kerkyra',
      'Lefkas',
      'Zakynthos',
      'Ipeiros',
      'Arta',
      'Ioannina',
      'Preveza',
      'Thesprotia',
      'Kentriki Makedonia',
      'Chalkidiki',
      'Imathia',
      'Kilkis',
      'Pella',
      'Pieria',
      'Serrai',
      'Thessaloniki',
      'Kriti',
      'Chania',
      'Irakleion',
      'Lasithion',
      'Rethymnon',
      'Notio Aigaio',
      'Dodekanisos',
      'Kyklades',
      'Peloponnisos',
      'Argolis',
      'Arkadia',
      'Korinthia',
      'Lakonia',
      'Messinia',
      'Sterea Ellada',
      'Evrytania',
      'Evvoia',
      'Fokis',
      'Fthiotis',
      'Voiotia',
      'Thessalia',
      'Karditsa',
      'Larisa',
      'Magnisia',
      'Trikala',
      'Voreio Aigaio',
      'Chios',
      'Lesvos',
      'Samos',
    ],
  },
  {
    name: 'Greenland',
    provinces: ['Greenland'],
  },
  {
    name: 'Grenada',
    provinces: ['Grenada'],
  },
  {
    name: 'Guadeloupe',
    provinces: ['Guadeloupe'],
  },
  {
    name: 'Guam',
    provinces: ['Guam'],
  },
  {
    name: 'Guatemala',
    provinces: [
      'Alta Verapaz',
      'Baja Verapaz',
      'Chimaltenango',
      'Chiquimula',
      'El Progreso',
      'Escuintla',
      'Guatemala',
      'Huehuetenango',
      'Izabal',
      'Jalapa',
      'Jutiapa',
      'Petén',
      'Quezaltenango',
      'Quiché',
      'Retalhuleu',
      'Sacatepéquez',
      'San Marcos',
      'Santa Rosa',
      'Sololá',
      'Suchitepéquez',
      'Totonicapán',
      'Zacapa',
    ],
  },
  {
    name: 'Guinea',
    provinces: [
      'Bake, Gouvernorat de',
      'Boffa',
      'Boké',
      'Fria',
      'Gaoual',
      'Kindia',
      'Conakry, Gouvernorat de',
      'Faranah, Gouvernorat de',
      'Dabola',
      'Dinguiraye',
      'Faranah',
      'Kissidougou',
      'Kankan, Gouvernorat de',
      'Kankan',
      'Kérouané',
      'Kouroussa',
      'Mandiana',
      'Siguiri',
      'Kindia, Gouvernorat de',
      'Coyah',
      'Dubréka',
      'Forécariah',
      'Télimélé',
      'Labé, Gouvernorat de',
      'Koubia',
      'Labé',
      'Lélouma',
      'Mali',
      'Tougué',
      'Mamou, Gouvernorat de',
      'Dalaba',
      'Mamou',
      'Pita',
      'Nzérékoré, Gouvernorat de',
      'Beyla',
      'Guékédou',
      'Lola',
      'Macenta',
      'Nzérékoré',
      'Yomou',
    ],
  },
  {
    name: 'Guinea-Bissau',
    provinces: [
      'Bissau',
      'Bafatá',
      'Biombo',
      'Bolama',
      'Cacheu',
      'Gabú',
      'Oio',
      'Quinara',
    ],
  },
  {
    name: 'Guyana',
    provinces: [
      'Barima-Waini',
      'Cuyuni-Mazaruni',
      'Demerara-Mahaica',
      'East Berbice-Corentyne',
      'Essequibo Islands-West Demerara',
      'Mahaica-Berbice',
      'Pomeroon-Supenaam',
      'Potaro-Siparuni',
      'Upper Demerara-Berbice',
      'Upper Takutu-Upper Essequibo',
    ],
  },
  {
    name: 'Haiti',
    provinces: [
      'Artibonite',
      'Centre',
      'Grande-Anse',
      'Nord',
      'Nord-Est',
      'Nord-Ouest',
      'Ouest',
      'Sud',
      'Sud-Est',
    ],
  },
  {
    name: 'Heard & McDonald Islands',
    provinces: ['Heard & McDonald Islands'],
  },
  {
    name: 'Vatican City (Holy See)',
    provinces: ['Vatican City (Holy See)'],
  },
  {
    name: 'Honduras',
    provinces: [
      'Atlántida',
      'Colón',
      'Comayagua',
      'Copán',
      'Cortés',
      'Choluteca',
      'El Paraíso',
      'Francisco Morazán',
      'Gracias a Dios',
      'Intibucá',
      'Islas de la Bahía',
      'La Paz',
      'Lempira',
      'Ocotepeque',
      'Olancho',
      'Santa Bárbara',
      'Valle',
      'Yoro',
    ],
  },
  {
    name: 'Hong Kong',
    provinces: ['Hong Kong'],
  },
  {
    name: 'Hungary',
    provinces: [
      'Budapest',
      'Bács-Kiskun',
      'Baranya',
      'Békés',
      'Borsod-Abaúj-Zemplén',
      'Csongrád',
      'Fejér',
      'Gyór-Moson-Sopron',
      'Hajdú-Bihar',
      'Heves',
      'Jasz-Nagykun-Szolnok',
      'Komárom-Esztergom',
      'Nógrád',
      'Pest',
      'Somogy',
      'Szabolcs-Szatmár-Bereg',
      'Tolna',
      'Vas',
      'Veszprém',
      'Zala',
      'Békéscsaba',
      'Debrecen',
      'Dunaújváros',
      'Eger',
      'Gyór',
      'Hódmezóvásárhely',
      'Kaposvár',
      'Kecskemét',
      'Miskolc',
      'Nagykanizsa',
      'Nyíregyháza',
      'Pécs',
      'Salgótarján',
      'Sopron',
      'Szeged',
      'Székesfehérvár',
      'Szekszárd',
      'Szolnok',
      'Szombathely',
      'Tatabánya',
      'Veszprém',
      'Zalaegerszeg',
    ],
  },
  {
    name: 'Iceland',
    provinces: [
      'Austurland',
      'Höfudborgarsvædi utan Reykjavíkur',
      'Nordurland eystra',
      'Nordurland vestra',
      'Reykjavīk',
      'Sudurland',
      'Sudurnes',
      'Vestfirdir',
      'Vesturland',
    ],
  },
  {
    name: 'India',
    provinces: [
      'Andhra Pradesh',
      'Arunachal Pradesh',
      'Assam',
      'Bihar',
      'Goa',
      'Gujarat',
      'Haryana',
      'Himachal Pradesh',
      'Jammu and Kashmir',
      'Karnataka',
      'Kerala',
      'Madhya Pradesh',
      'Maharashtra',
      'Manipur',
      'Meghalaya',
      'Mizoram',
      'Nagaland',
      'Orissa',
      'Punjab',
      'Rajasthan',
      'Sikkim',
      'Tamil Nadu',
      'Tripura',
      'Uttar Pradesh',
      'West Bengal',
      'Andaman and Nicobar Islands',
      'Chandigarh',
      'Dadra and Nagar Haveli',
      'Daman and Diu',
      'Delhi',
      'Lakshadweep',
      'Pondicherry',
    ],
  },
  {
    name: 'Indonesia',
    provinces: [
      'Irian Jaya',
      'Irian Jaya',
      'Jawa',
      'Jawa Barat',
      'Jawa Tengah',
      'Jawa Timur',
      'Jakarta Raya',
      'Yogyakarta',
      'Kalimantan',
      'Kalimantan Barat',
      'Kalimantan Selatan',
      'Kalimantan Tengah',
      'Kalimantan Timur',
      'Maluku',
      'Maluku',
      'Nusa Tenggara',
      'Bali',
      'Nusa Tenggara Barat',
      'Nusa Tenggara Timur',
      'Timor Timur',
      'Sulawesi',
      'Sulawesi Selatan',
      'Sulawesi Tengah',
      'Sulawesi Tenggara',
      'Sulawesi Utara',
      'Sumatera',
      'Bengkulu',
      'Jambi',
      'Lampung',
      'Riau',
      'Sumatera Barat',
      'Sumatera Selatan',
      'Sumatera Utara',
      'Aceh',
    ],
  },
  {
    name: 'Iran',
    provinces: [
      'Ardabīl',
      'Āzarbāyjān-e-Gharbī',
      'Āzarbāyjān-e-Sharqī',
      'Būshehr',
      'Chahār Maḩāll vā Bakhtīārī',
      'Eşfahān',
      'Fārs',
      'Gīlān',
      'Hamadān',
      'Hormozgān',
      'Īlām',
      'Kermān',
      'Kermānshāhān',
      'Khorāsān',
      'Khūzestān',
      'Kohkīlūyeh va Būyer Aḩmadī',
      'Kordestān',
      'Lorestān',
      'Markazī',
      'Māzandarān',
      'Qom',
      'Semnān',
      'Sīstān va Balūchestān',
      'Tehrān',
      'Yazd',
      'Zanjān',
    ],
  },
  {
    name: 'Iraq',
    provinces: [
      'Al Anbār',
      'Al Başrah',
      'Al Muthanná',
      'Al Qādisīyah',
      'An Najaf',
      'Arbīl',
      'As Sulaymānīyah',
      "At Ta'mīm",
      'Bābil',
      'Baghdād',
      'Dahūk',
      'Dhī Qār',
      'Diyālá',
      "Karbalā'",
      'Maysān',
      'Nīnawá',
      'Şalāḩ ad Dīn',
      'Wāsiţ',
    ],
  },
  {
    name: 'Ireland',
    provinces: [
      'Connaught (Connacht)',
      'Galway (Gaillimh)',
      'Leitrim (Liatroim)',
      'Mayo (Maigh Eo)',
      'Roscommon (Ros Comáin)',
      'Sligo (Sligeach)',
      'Leinster (Laighin)',
      'Carlow (Ceatharlach)',
      'Dublin (Baile Átha Cliath)',
      'Kildare (Cill Dara)',
      'Kilkenny (Cill Chainnigh)',
      'Laois (Laois)',
      'Longford (An Longfort)',
      'Louth (Lú)',
      'Meath (An Mhí)',
      'Offaly (Uíbh Fhailí)',
      'Westmeath (An Iarmhí)',
      'Wexford (Loch Garman)',
      'Wicklow (Cill Mhantáin)',
      'Munster (An Mhumhain)',
      'Ulster (Ulaidh)',
      'Cavan (An Cabhán)',
      'Donegal (Dún na nGall)',
      'Monaghan (Muineachán)',
    ],
  },
  {
    name: 'Israel',
    provinces: [
      'HaDarom (El Janūbī)',
      'HaMerkaz (El Awsat)',
      'HaZafon (Esh Shamālī)',
      'Hefa (Heifā)',
      'Tel-Aviv (Tell Abīb)',
      'Yerushalayim (Al Quds)',
    ],
  },
  {
    name: 'Italia',
    provinces: [
      'Abruzzo',
      'Chieti',
      "L'Aquila",
      'Pescara',
      'Teramo',
      'Basilicata',
      'Matera',
      'Potenza',
      'Calabria',
      'Catanzaro',
      'Cosenza',
      'Crotone',
      'Reggio Calabria',
      'Vibo Valentia',
      'Campania',
      'Avellino',
      'Benevento',
      'Caserta',
      'Napoli',
      'Salerno',
      'Emilia-Romagna',
      'Bologna',
      'Ferrara',
      'Forlì',
      'Modena',
      'Parma',
      'Piacenza',
      'Ravenna',
      'Reggio Emilia',
      'Rimini',
      'Friuli-Venezia Giulia',
      'Gorizia',
      'Pordenone',
      'Trieste',
      'Udine',
      'Lazio',
      'Frosinone',
      'Latina',
      'Rieti',
      'Roma',
      'Viterbo',
      'Liguria',
      'Genova',
      'Imperia',
      'La Spezia',
      'Savona',
      'Lombardia',
      'Bergamo',
      'Brescia',
      'Como',
      'Cremona',
      'Lecco',
      'Lodi',
      'Mantova',
      'Milano',
      'Pavia',
      'Sondrio',
      'Varese',
      'Marche',
      'Ancona',
      'Ascoli Piceno',
      'Macerata',
      'Pesaro',
      'Molise',
      'Campobasso',
      'Isernia',
      'Piemonte',
      'Alessandria',
      'Asti',
      'Biella',
      'Cuneo',
      'Novara',
      'Torino',
      'Verbano-Cusio-Ossola',
      'Vercelli',
      'Puglia',
      'Bari',
      'Brindisi',
      'Foggia',
      'Lecce',
      'Taranto',
      'Sardegna',
      'Cagliari',
      'Nuoro',
      'Oristano',
      'Sassari',
      'Sicilia',
      'Agrigento',
      'Caltanissetta',
      'Catania',
      'Enna',
      'Mesaina',
      'Palermo',
      'Ragusa',
      'Siracusa',
      'Trapani',
      'Toscana',
      'Arezzo',
      'Firenze',
      'Grosseto',
      'Livorno',
      'Lucca',
      'Massa',
      'Pisa',
      'Pistoia',
      'Prato',
      'Siena',
      'Trentino-Alte Adige (Trentino-Südtirol)',
      'Bolzano (Bozen)',
      'Trento',
      'Umbria',
      'Perugia',
      'Terni',
      "Valle d'Aosta (Vallée d'Aoste)",
      'Aosta (Aoste)',
      'Veneto',
      'Belluno',
      'Padova',
      'Rovigo',
      'Treviso',
      'Venezia',
      'Verona',
      'Vicenza',
    ],
  },
  {
    name: 'Jamaica',
    provinces: [
      'Clarendon',
      'Hanover',
      'Kingston',
      'Manchester',
      'Portland',
      'Saint Andrew',
      'Saint Ann',
      'Saint Catherine',
      'Saint Elizabeth',
      'Saint James',
      'Saint Mary',
      'Saint Thomas',
      'Trelawny',
      'Westmoreland',
    ],
  },
  {
    name: 'Japan',
    provinces: [
      'Aiti [Aichi]',
      'Akita',
      'Aomori',
      'Ehime',
      'Gihu [Gifu]',
      'Gunma',
      'Hirosima [Hiroshima]',
      'Hokkaidô [Hokkaido]',
      'Hukui [Fukui]',
      'Hukuoka [Fukuoka]',
      'Hukusima [Fukushima]',
      'Hyôgo [Hyogo]',
      'Ibaraki',
      'Isikawa [Ishikawa]',
      'Iwate',
      'Kagawa',
      'Kagosima [Kagoshima]',
      'Kanagawa',
      'Kôti [Kochi]',
      'Kumamoto',
      'Kyôto [Kyoto]',
      'Mie',
      'Miyagi',
      'Miyazaki',
      'Nagano',
      'Nagasaki',
      'Nara',
      'Niigata',
      'Ôita [Oita]',
      'Okayama',
      'Okinawa',
      'Ôsaka [Osaka]',
      'Saga',
      'Saitama',
      'Siga [Shiga]',
      'Sizuoka [Shizuoka]',
      'Tiba [Chiba]',
      'Totigi [Tochigi]',
      'Tokusima [Tokushima]',
      'Tôkyô [Tokyo]',
      'Tottori',
      'Toyama',
      'Wakayama',
      'Yamagata',
      'Yamaguti [Yamaguchi]',
      'Yamanasi [Yamanashi]',
    ],
  },
  {
    name: 'Jordan',
    provinces: [
      '‘Ajlūn',
      "Al 'Aqaba",
      "Al Balqā'",
      'Al Karak',
      'Al Mafraq',
      '‘Ammān',
      'Aţ Ţafīlah',
      "Az Zarqā'",
      'Irbid',
      'Jarash',
      'Ma‘ān',
      'Mādaba',
    ],
  },
  {
    name: 'Kazakhstan',
    provinces: [
      'Almaty',
      'Bayqonyr (Baykonyr)',
      "Almaty oblysy (Almatinskaya oblast')",
      "Aqmola oblysy (Akmolinskaya oblast')",
      "Aqtöbe oblysy (Aktyubinskaya oblast')",
      "Atyraü oblysy (Atyrauskaya oblast')",
      "Batys Kazakstan oblysy (Zapadno-Kazakhstanskaya oblast')",
      "Mangghystaū oblysy (Mangystauskaya oblast')",
      "Ongtüstik Kazakstan oblysy (Yuzhno-Kazakhstanskaya oblast')",
      "Pavlodar oblysy (Pavlodarskaya oblast')",
      "Qaraghandy oblysy (Karagandinskaya oblast')",
      "Qostanay oblysy (Kustanayskaya oblast')",
      "Qyzylorda oblysy (Kzylordinskaya oblast')",
      "Shyghys Kazakstan oblysy (Vostochno-Kazakhstanskaya oblast')",
      "Soltüstik Kazakstan oblysy (Severo-Kazakhstanskaya oblast')",
      "Zhambyl oblysy (Zhambylskaya Oblast')",
    ],
  },
  {
    name: 'Kenya',
    provinces: [
      'Nairobi Municipality',
      'Central (Kati)',
      'Coast (Pwani)',
      'Eastern (Mashariki)',
      'North-Eastern (Kaskazini Mashariki)',
      'Nyanza',
      'Rift Valley',
      'Western (Magharibi)',
    ],
  },
  {
    name: 'Kiribati',
    provinces: ['Gilbert Islands', 'Line Islands', 'Phoenix Islands'],
  },
  {
    name: 'Korea (North)',
    provinces: [
      'Kaesong-si',
      'Nampo-si',
      'Pyongyang-si',
      'Chagang-do',
      'Hamgyongbuk-do',
      'Hamgyongnam-do',
      'Hwanghaebuk-do',
      'Hwanghaenam-do',
      'Kangwon-do',
      'Pyonganbuk-do',
      'Pyongannam-do',
      'Yanggang-do',
    ],
  },
  {
    name: 'Korea (South)',
    provinces: [
      'Seoul Teugbyeolsi [ Seoul-T’ŭkpyŏlshi]',
      "Busan Gwang'yeogsi [Pusan-Kwangyŏkshi]",
      "Daegu Gwang'yeogsi [Taegu-Kwangyŏkshi)",
      "Daejeon Gwang'yeogsi [Taejŏn-Kwangyŏkshi]",
      "Gwangju Gwang'yeogsi [Kwangju-Kwangyŏkshi]",
      "Incheon Gwang'yeogsi [Inchŏn-Kwangyŏkshi]",
      "Ulsan Gwang'yeogsi [Ulsan-Kwangyŏkshi]",
      "Chungcheongbugdo [Ch'ungch'ŏngbuk-do]",
      "Chungcheongnamdo [Ch'ungch'ŏngnam-do]",
      "Gang'weondo [Kang-won-do]",
      'Gyeonggido [Kyŏnggi-do]',
      'Gyeongsangbugdo [Kyŏngsangbuk-do]',
      'Gyeongsangnamdo [Kyŏngsangnam-do]',
      'Jejudo [Cheju-do]',
      'Jeonrabugdo [Chŏllabuk-do)',
      'Jeonranamdo [Chŏllanam-do]',
    ],
  },
  {
    name: 'Kuwait',
    provinces: [
      'Al Aḩmadi',
      'Al Farwānīyah',
      'Al Jahrah',
      'Al Kuwayt',
      'Ḩawallī',
    ],
  },
  {
    name: 'Kyrgyzstan',
    provinces: [
      "Chu (Chuyskaya oblast')",
      "Jalal-Abad (Dzhalal-Abadskaya oblast')",
      'Naryn (Narynskaya Oblast’)',
      "Osh (Oshskaya oblast')",
      "Talas (Talasskaya oblast')",
      "Ysyk-Köl (Issyk-Kul'skaya oblast')",
    ],
  },
  {
    name: 'Laos',
    provinces: [
      'Vientiane',
      'Attapu [Attopeu]',
      'Bokèo',
      'Bolikhamxai [Borikhane]',
      'Champasak [Champassak]',
      'Houaphan',
      'Khammouan',
      'Louang Namtha',
      'Louangphabang [Louang Prabang]',
      'Oudômxai [Oudomsai]',
      'Phôngsali [Phong Saly]',
      'Salavan [Saravane]',
      'Savannakhét',
      'Vientiane',
      'Xaignabouli [Sayaboury]',
      'Xékong [Sékong]',
      'Xiangkhoang [Xieng Khouang]',
    ],
  },
  {
    name: 'Latvia',
    provinces: [
      'Aizkraukles Aprinkis',
      'Alūksnes Aprinkis',
      'Balvu Aprinkis',
      'Bauskas Aprinkis',
      'Cēsu Aprinkis',
      'Daugavpils Aprinkis',
      'Dobeles Aprinkis',
      'Gulbenes Aprinkis',
      'Jelgavas Aprinkis',
      'Jēkabpils Aprinkis',
      'Krāslavas Aprinkis',
      'Kuldīgas Aprinkis',
      'Limbažu Aprinkis',
      'Liepājas Aprinkis',
      'Ludzas Aprinkis',
      'Madonas Aprinkis',
      'Ogres Aprinkis',
      'Preilu Aprinkis',
      'Rēzeknes Aprinkis',
      'Rīgas Aprinkis',
      'Saldus Aprinkis',
      'Talsu Aprinkis',
      'Tukuma Aprinkis',
      'Valkas Aprinkis',
      'Valmieras Aprinkis',
      'Ventspils Aprinkis',
      'Daugavpils',
      'Jelgava',
      'Jūrmala',
      'Liepāja',
      'Rēzekne',
      'Rīga',
      'Ventspils',
    ],
  },
  {
    name: 'Lebanon',
    provinces: [
      'Beiroût (Bayrūt)',
      "El Béqaa (Al Biqā')",
      'Jabal Loubnâne (Jabal Lubnān)',
      'Loubnâne ech Chemâli (Ash Shamāl)',
      'Loubnâne ej Jnoûbi (Al Janūb)',
      'Nabatîyé (An Nabaţīyah',
    ],
  },
  {
    name: 'Lesotho',
    provinces: [
      'Berea',
      'Butha-Buthe',
      'Leribe',
      'Mafeteng',
      'Maseru',
      "Mohale's Hoek",
      'Mokhotlong',
      "Qacha's Nek",
      'Quthing',
      'Thaba-Tseka',
    ],
  },
  {
    name: 'Liberia',
    provinces: [
      'Bomi',
      'Bong',
      'Grand Bassa',
      'Grand Cape Mount',
      'Grand Gedeh',
      'Grand Kru',
      'Lofa',
      'Margibi',
      'Maryland',
      'Montserrado',
      'Nimba',
      'Rivercess',
      'Sinoe',
    ],
  },
  {
    name: 'Libya',
    provinces: [
      'Al Buţnān',
      'Al Jabal al Akhḑar',
      'Al Jabal al Gharbī',
      'Al Jufrah',
      'Al Wāḩah',
      'Al Wusţá',
      'Az Zāwiyah',
      'Banghāzī',
      'Fazzān',
      'Mişrātah',
      'Naggaza',
      'Sawfajjin',
      'Ţarābulus',
    ],
  },
  {
    name: 'Liechtenstein',
    provinces: ['Liechtenstein'],
  },
  {
    name: 'Lithuania',
    provinces: [
      'Alytaus Apskritis',
      'Kauno Apskritis',
      'Klaipėdos Apskritis',
      'Marijampolės Apskritis',
      'Panevėžio Apskritis',
      'Šiauliu Apskritis',
      'Tauragės Apskritis',
      'Telšiu Apskritis',
      'Utenos Apskritis',
      'Vilniaus Apskritis',
    ],
  },
  {
    name: 'Luxembourg',
    provinces: ['Diekirch', 'Grevenmacher', 'Luxembourg (Luxemburg)'],
  },
  {
    name: 'Macau',
    provinces: ['Macau'],
  },
  {
    name: 'Macedonia',
    provinces: ['Macedonia'],
  },
  {
    name: 'Madagascar',
    provinces: [
      'Antananarivo',
      'Antsiranana',
      'Fianarantsoa',
      'Mahajanga',
      'Toamasina',
      'Toliara',
    ],
  },
  {
    name: 'Malawi',
    provinces: [
      'Central',
      'Dedza',
      'Dowa',
      'Kasungu',
      'Lilongwe',
      'Mchinji',
      'Nkhotakota',
      'Ntcheu',
      'Ntchisi',
      'Salima',
      'Northern',
      'Chitipa',
      'Karonga',
      'Mzimba',
      'Nkhata Bay',
      'Rumphi',
      'Southern',
      'Blantyre',
      'Chikwawa',
      'Chiradzulu',
      'Machinga',
      'Mangochi',
      'Mulanje',
      'Mwanza',
      'Nsanje',
      'Thyolo',
      'Zomba',
    ],
  },
  {
    name: 'Malaysia',
    provinces: [
      'Wilayah Persekutuan Kuala Lumpur',
      'Wilayah Persekutuan Labuan',
      'Johor',
      'Kedah',
      'Kelantan',
      'Melaka',
      'Negeri Sembilan',
      'Pahang',
      'Perak',
      'Perlis',
      'Pulau Pinang',
      'Sabah',
      'Sarawak',
      'Selangor',
      'Terengganu',
    ],
  },
  {
    name: 'Maldives',
    provinces: [
      'Male',
      'Alif',
      'Baa',
      'Dhaalu',
      'Faafu',
      'Gaaf Alif',
      'Gaafu Dhaalu',
      'Gnaviyani',
      'Haa Alif',
      'Haa Dhaalu',
      'Kaafu',
      'Laamu',
      'Lhaviyani',
      'Meemu',
      'Noonu',
      'Raa',
      'Seenu',
      'Shaviyani',
      'Thaa',
      'Vaavu',
    ],
  },
  {
    name: 'Mali',
    provinces: [
      'Bamako',
      'Gao',
      'Kayes',
      'Kidal',
      'Koulikoro',
      'Mopti',
      'Ségou',
      'Sikasso',
      'Tombouctou',
    ],
  },
  {
    name: 'Malta',
    provinces: ['Malta'],
  },
  {
    name: 'Marshall Islands',
    provinces: [
      'Ralik chain',
      'Ailinglapalap',
      'Ebon',
      'Eniwetok',
      'Jaluit',
      'Kili',
      'Kwajalein',
      'Lae',
      'Lib',
      'Namorik',
      'Namu',
      'Rongelap',
      'Ujae',
      'Ujelang',
      'Wotho',
      'Ratak chain',
      'Ailuk',
      'Arno',
      'Aur',
      'Likiep',
      'Majuro',
      'Maloelap',
      'Mejit',
      'Mili',
      'Utirik',
      'Wotje',
    ],
  },
  {
    name: 'Martinique',
    provinces: ['Martinique'],
  },
  {
    name: 'Mauritania',
    provinces: [
      'Nouakchott',
      'Adrar',
      'Assaba',
      'Brakna',
      'Dakhlet Nouādhibou',
      'Gorgol',
      'Guidimaka',
      'Hodh ech Chargui',
      'Hodh el Gharbi',
      'Inchiri',
      'Tagant',
      'Tiris Zemmour',
      'Trarza',
    ],
  },
  {
    name: 'Mauritius',
    provinces: [
      'Beau Bassin-Rose Hill',
      'Curepipe',
      'Port Louis',
      'Quatre Bornes',
      'Vacoas-Phoenix',
      'Black River',
      'Flacq',
      'Grand Port',
      'Moka',
      'Pamplemousses',
      'Plaines Wilhems',
      'Rivière du Rempart',
      'Savanne',
      'Agalega Islands',
      'Cargados Carajos Shoals [Saint Brandon Islands]',
      'Rodrigues Island',
    ],
  },
  {
    name: 'Mayotte',
    provinces: ['Mayotte'],
  },
  {
    name: 'Mexico',
    provinces: [
      'Distrito Federal',
      'Aguascalientes',
      'Baja California',
      'Baja California Sur',
      'Campeche',
      'Coahuila',
      'Colima',
      'Chiapas',
      'Chihuahua',
      'Durango',
      'Guerrero',
      'Guanajuato',
      'Hidalgo',
      'Jalisco',
      'México',
      'Michoacán',
      'Morelos',
      'Nayarit',
      'Nuevo León',
      'Oaxaca',
      'Puebla',
      'Queretaro',
      'Quintana Roo',
      'San Luis Potosí',
      'Sinaloa',
      'Sonora',
      'Tabasco',
      'Tamaulipas',
      'Tlaxcala',
      'Veracruz',
      'Yucatán',
      'Zacatecas',
    ],
  },
  {
    name: 'Micronesia',
    provinces: ['chuuk', 'Kosrae', 'Pohnpei', 'Yap'],
  },
  {
    name: 'Moldova',
    provinces: [
      'Bălţi',
      'Cahul',
      'Chişinău',
      'Dubăsari',
      'Orhei',
      'Rîbniţa',
      'Soroca',
      'Tighina',
      'Tiraspol',
      'Ungheni',
      'Anenii Noi',
      'Basarabeasca',
      'Brinceni',
      'Cahul',
      'Camenca',
      'Cantemir',
      'Căinari',
      'Călăraşi',
      'Căuşeni',
      'Ciadîr-Lunga',
      'Cimişlia',
      'Comrat',
      'Criuleni',
      'Donduşeni',
      'Drochia',
      'Dubăsari',
      'Edineţ',
      'Făleşti',
      'Floreşti',
      'Glodeni',
      'Grigoriopol',
      'Hînceşti',
      'Ialoveni',
      'Leova',
      'Nisporeni',
      'Ocniţa',
      'Orhei',
      'Rezina',
      'Rîbniţa',
      'Rîşcani',
      'Sîngerei',
      'Slobozia',
      'Soroca',
      'Străşeni',
      'Şoldăneşti',
      'Ştefan Vodă',
      'Taraclia',
      'Teleneşti',
      'Ungheni',
      'Vulcăneşti',
    ],
  },
  {
    name: 'Monaco',
    provinces: ['Monaco'],
  },
  {
    name: 'Mongolia',
    provinces: [
      'Ulaanbaatar',
      'Arhangay',
      'Bayanhongor',
      'Bayan-Ölgiy',
      'Bulgan',
      'Darhan uul',
      'Dornod',
      'Dornogovĭ',
      'Dundgovĭ',
      'Dzavhan',
      'Govĭ-Altay',
      'Govĭ-Sümber',
      'Hentiy',
      'Hovd',
      'Hövsgöl',
      'Ömnögovĭ',
      'Orhon',
      'Övörhangay',
      'Selenge',
      'Sühbaatar',
      'Töv',
      'Uvs',
    ],
  },
  {
    name: 'Montserrat',
    provinces: ['Montserrat'],
  },
  {
    name: 'Morocco',
    provinces: [
      'Centre',
      'Azilal',
      'Beni Mellal',
      'Ben Slimane',
      'Boulemane',
      'Casablanca [Dar el Beïda]',
      'El Jadida',
      'Khouribga',
      'Settat',
      'Centre-Nord',
      'Al Hoceïma',
      'Fès',
      'Sefrou',
      'Taounate',
      'Taza',
      'Centre-Sud',
      'El Hajeb',
      'Errachidia',
      'Ifrane',
      'Khenifra',
      'Meknès',
      'Est',
      'Berkane',
      'Figuig',
      'Jrada',
      'Nador',
      'Oujda',
      'Nord-Ouest',
      'Chefchaouene',
      'Kénitra',
      'Khemisset',
      'Larache',
      'Rabat-Salé',
      'Sidi Kacem',
      'Tanger',
      'Tétouan',
      'Sud',
      'Agadir',
      'Aït Baha',
      'Aït Melloul',
      'Assa-Zag',
      'Boujdour (EH)',
      'Es Semara (EH)',
      'Guelmim',
      'Laayoune (EH)',
      'Ouarzazate',
      'Oued ed Dahab (EH)',
      'Tan-Tan',
      'Taroudannt',
      'Tata',
      'Tiznit',
      'Tensift',
      'Al Haouz',
      'Chichaoua',
      'Essaouira',
      'Kelaat Sraghna',
      'Marrakech',
      'Safi',
    ],
  },
  {
    name: 'Mozambique',
    provinces: [
      'Maputo',
      'Cabo Delgado',
      'Gaza',
      'Inhambane',
      'Manica',
      'Maputo',
      'Nampula',
      'Niassa',
      'Sofala',
      'Tete',
      'Zambézia',
    ],
  },
  {
    name: 'Myanmar',
    provinces: [
      'Ayeyarwady',
      'Bago',
      'Magway',
      'Mandalay',
      'Sagaing',
      'Tanintharyi',
      'Yangon',
      'Chin',
      'Kachin',
      'Kayah',
      'Kayin',
      'Mon',
      'Rakhine',
      'Shan',
    ],
  },
  {
    name: 'Namibia',
    provinces: [
      'Caprivi',
      'Erongo',
      'Hardap',
      'Karas',
      'Khomas',
      'Kunene',
      'Ohangwena',
      'Okavango',
      'Omaheke',
      'Omusati',
      'Oshana',
      'Oshikoto',
      'Otjozondjupa',
    ],
  },
  {
    name: 'Nauru',
    provinces: ['Nauru'],
  },
  {
    name: 'Nepal',
    provinces: [
      'Madhyamanchal',
      'Bagmati',
      'Janakpur',
      'Narayani',
      'Madhya Pashchimanchal',
      'Bheri',
      'Karnali',
      'Rapti',
      'Pashchimanchal',
      'Dhawalagiri',
      'Gandaki',
      'Lumbini',
      'Purwanchal',
      'Kosi [Koshi]',
      'Mechi',
      'Sagarmatha',
      'Sudur Pashchimanchal',
      'Mahakali',
      'Seti',
    ],
  },
  {
    name: 'Netherlands',
    provinces: [
      'Drenthe',
      'Flevoland',
      'Friesland',
      'Gelderland',
      'Groningen',
      'Limburg',
      'Noord-Brabant',
      'Noord-Holland',
      'Overijssel',
      'Utrecht',
      'Zeeland',
      'Zuid-Holland',
    ],
  },
  {
    name: 'Netherlands Antilles',
    provinces: ['Netherlands Antilles'],
  },
  {
    name: 'New Caledonia',
    provinces: ['New Caledonia'],
  },
  {
    name: 'New Zealand',
    provinces: [
      'North Island',
      'Auckland',
      'Bay of Plenty',
      'Gisborne',
      "Hawkes's Bay",
      'Manawatu-Wanganui',
      'Northland',
      'Taranaki',
      'Waikato',
      'Wellington',
      'South Island',
      'Canterbury',
      'Marlborough',
      'Nelson',
      'Otago',
      'Southland',
      'Tasman',
      'West Coast',
    ],
  },
  {
    name: 'Nicaragua',
    provinces: [
      'Boaco',
      'Carazo',
      'Chinandega',
      'Chontales',
      'Estelí',
      'Granada',
      'Jinotega',
      'León',
      'Madriz',
      'Manaqua',
      'Masaya',
      'Matagalpa',
      'Nueva Segovia',
      'Río San Juan',
      'Rivas',
      'Zelaya',
    ],
  },
  {
    name: 'Niger',
    provinces: [
      'Niamey',
      'Agadez',
      'Diffa',
      'Dosso',
      'Maradi',
      'Tahoua',
      'Tillaberi',
      'Zinder',
    ],
  },
  {
    name: 'Nigeria',
    provinces: [
      'Abuja Capital Territory',
      'Abia',
      'Adamawa',
      'Akwa Ibom',
      'Anambra',
      'Bauchi',
      'Benue',
      'Borno',
      'Cross River',
      'Delta',
      'Edo',
      'Enugu',
      'Imo',
      'Jigawa',
      'Kaduna',
      'Kano',
      'Katsina',
      'Kebbi',
      'Kogi',
      'Kwara',
      'Lagos',
      'Niger',
      'Ogun',
      'Ondo',
      'Osun',
      'Oyo',
      'Plateau',
      'Rivers',
      'Sokoto',
      'Taraba',
      'Yobe',
    ],
  },
  {
    name: 'Niue',
    provinces: ['Niue'],
  },
  {
    name: 'Norfolk Island',
    provinces: ['Norfolk Island'],
  },
  {
    name: 'Northern Mariana Islands',
    provinces: ['Northern Mariana Islands'],
  },
  {
    name: 'Norway',
    provinces: [
      'Akershus',
      'Aust-Agder',
      'Buskerud',
      'Finnmark',
      'Hedmark',
      'Hordaland',
      'Møre og Romsdal',
      'Nordland',
      'Nord-Trøndelag',
      'Oppland',
      'Oslo',
      'Rogaland',
      'Sogn og Fjordane',
      'Sør-Trøndelag',
      'Telemark',
      'Troms',
      'Vest-Agder',
      'Vestfold',
      'Østfold',
      'Jan Mayen (Arctic Region)',
      'Svalbard (Arctic Region)',
    ],
  },
  {
    name: 'Oman',
    provinces: [
      'Ad Dākhilīyah',
      'Al Bāţinah',
      'Al Janūbīyah [Zufār]',
      'Al Wusţā',
      'Ash Sharqīyah',
      'Az Zāhirah',
      'Masqaţ',
      'Musandam',
    ],
  },
  {
    name: 'Pakistan',
    provinces: [
      'Islamabad',
      'Baluchistan (Balochistān)',
      'North-West Frontier',
      'Punjab',
      'Sind (Sindh)',
      'Federally Administered Tribal Areas',
      'Azad Kashmir',
      'Northern Areas',
    ],
  },
  {
    name: 'Palau',
    provinces: ['Palau'],
  },
  {
    name: 'Panama',
    provinces: [
      'Botas del Toro',
      'Coclé',
      'Colón',
      'Chiriquī',
      'Darién',
      'Herrera',
      'Los Santos',
      'Panamá',
      'Veraguas',
      'Comarca de San Blas',
    ],
  },
  {
    name: 'Papua New Guinea',
    provinces: [
      'National Capital District (Port Moresby)',
      'Central',
      'Chimbu',
      'Eastern Highlands',
      'East New Britain',
      'East Sepik',
      'Enga',
      'Gulf',
      'Madang',
      'Manus',
      'Milne Bay',
      'Morobe',
      'New Ireland',
      'Northern',
      'North Solomons',
      'Sandaun [West Sepik]',
      'Southern Highlands',
      'Western',
      'Western Highlands',
      'West New Britain',
    ],
  },
  {
    name: 'Paraguay',
    provinces: [
      'Asunción',
      'Alto Paraguay',
      'Alto Parang',
      'Amambay',
      'Boquerón',
      'Caaguazú',
      'Caazapá',
      'Canindeyú',
      'Central',
      'Concepción',
      'Cordillera',
      'Guairá',
      'Itapúa',
      'Misiones',
      'Neembucú',
      'Paraguarī',
      'Presidente Hayes',
      'San Pedro',
    ],
  },
  {
    name: 'Peru',
    provinces: [
      'El Callao',
      'Amazonas',
      'Ancash',
      'Apurímac',
      'Arequipa',
      'Ayacucho',
      'Cajamarca',
      'Cuzco [Cusco]',
      'Huancavelica',
      'Huánuco',
      'Ica',
      'Junín',
      'La Libertad',
      'Lambayeque',
      'Lima',
      'Loreto',
      'Madre de Dios',
      'Moquegua',
      'Pasco',
      'Piura',
      'Puno',
      'San Martín',
      'Tacna',
      'Tumbes',
      'Ucayali',
    ],
  },
  {
    name: 'Philippines',
    provinces: ['Philippines'],
  },
  {
    name: 'Pitcairn',
    provinces: ['Pitcairn'],
  },
  {
    name: 'Poland',
    provinces: [
      'Biała Podlaska',
      'Białystok',
      'Bielsko',
      'Bydgoszcz',
      'Chełm',
      'Ciechanów',
      'Czestochowa',
      'Elblag',
      'Gdańsk',
      'Gorzów',
      'Jelenia Gera',
      'Kalisz',
      'Katowice',
      'Kielce',
      'Konin',
      'Koszalin',
      'Kraków',
      'Krosno',
      'Legnica',
      'Leszno',
      'Lublin',
      'Łomia',
      'Łódź',
      'Nowy Sacz',
      'Olsztyn',
      'Opole',
      'Ostrołeka',
      'Piła',
      'Piotrków',
      'Płock',
      'Poznań',
      'Przemyśl',
      'Radom',
      'Rzeszów',
      'Siedlce',
      'Sieradz',
      'Skierniewice',
      'Słupsk',
      'Suwałki',
      'Szczecin',
      'Tarnobrzeg',
      'Tarnów',
      'Toruń',
      'Wałbrzych',
      'Warszawa',
      'Włocławek',
      'Wrocław',
      'Zamość',
      'Zielona Góra',
    ],
  },
  {
    name: 'Portugal',
    provinces: [
      'Aveiro',
      'Beja',
      'Braga',
      'Bragança',
      'Castelo Branco',
      'Coimbra',
      'Évora',
      'Faro',
      'Guarda',
      'Leiria',
      'Lisboa',
      'Portalegre',
      'Porto',
      'Santarém',
      'Setúbal',
      'Viana do Castelo',
      'Vila Real',
      'Viseu',
      'Regiāo Autónoma dos Açores',
      'Regiāo Autónoma da Madeira',
    ],
  },
  {
    name: 'Puerto Rico',
    provinces: ['Puerto Rico'],
  },
  {
    name: 'Qatar',
    provinces: [
      'Ad Dawḩah',
      'Al Ghuwayrīyah',
      'Al Jumaylīyah',
      'Al Khawr',
      'Al Wakrah',
      'Ar Rayyān',
      'Jarīyān al Bāţnah',
      'Madīnat ash Shamāl',
      'Umm Şalāl',
    ],
  },
  {
    name: 'Reunion',
    provinces: ['Reunion'],
  },
  {
    name: 'Romania',
    provinces: [
      'Bucureşti',
      'Alba',
      'Arad',
      'Argeş',
      'Bacău',
      'Bihor',
      'Bistriţa-Năsăud',
      'Botoşani',
      'Braşov',
      'Brăila',
      'Buzău',
      'Caraş-Severin',
      'Călăraşi',
      'Cluj',
      'Constanţa',
      'Covasna',
      'Dâmboviţa',
      'Dolj',
      'Galaţi',
      'Giurgiu',
      'Gorj',
      'Harghita',
      'Hunedoara',
      'Ialomiţa',
      'Iaşi',
      'Maramureş',
      'Mehedinţi',
      'Mureş',
      'Neamţ',
      'Olt',
      'Prahova',
      'Satu Mare',
      'Sălaj',
      'Sibiu',
      'Suceava',
      'Teleorman',
      'Timiş',
      'Tulcea',
      'Vaslui',
      'Vâlcea',
      'Vrancea',
    ],
  },
  {
    name: 'Russian Federation',
    provinces: [
      'Adygeya, Respublika',
      'Altay, Respublika',
      'Bashkortostan, Respublika',
      'Buryatiya, Respublika',
      'Chechenskaya Respublika',
      'Chuvashskaya Respublika',
      'Dagestan, Respublika',
      'Ingushskaya Respublika',
      'Kabardino-Balkarskaya Respublika',
      'Kalmykiya, Respublika',
      'Karachayevo-Cherkesskaya Respublika',
      'Kareliya, Respublika',
      'Khakasiya, Respublika',
      'Komi, Respublika',
      'Mariy El, Respublika',
      'Mordoviya, Respublika',
      'Sakha, Respublika [Yakutiya]',
      'Severnaya Osetiya, Respublika [Alaniya]',
      'Tatarstan, Respublika',
      'Tyva, Respublika [Tuva]',
      'Udmurtskaya Respublika',
      'Altayskiy kray',
      'Khabarovskiy kray',
      'Krasnodarskiy kray',
      'Krasnoyarskiy kray',
      'Primorskiy kray',
      "Stavropol 'skiy kray",
      "Amurskaya Oblast'",
      "Arkhangel'skaya Oblast'",
      "Astrakhanskaya Oblast'",
      "Belgorodskaya Oblast'",
      "Bryanskaya Oblast'",
      "Chelyabinskaya Oblast'",
      "Chitinskaya Oblast'",
      "Irkutskaya Oblast'",
      "Ivanovskaya Oblast'",
      "Kaliningradskaya Oblast'",
      "Kaluzhskaya Oblast'",
      "Kamchatskaya Oblast'",
      "Kemerovskaya Oblast'",
      "Kirovskaya Oblast'",
      "Kostromskaya Oblast'",
      "Kurganskaya Oblast'",
      "Kurskaya Oblast'",
      "Leningradskaya Oblast'",
      "Lipetskaya Oblast'",
      "Magadanskaya Oblast'",
      "Moskovskaya Oblast'",
      "Murmanskaya Oblast'",
      "Nizhegorodskaya Oblast'",
      "Novgorodskaya Oblast'",
      "Novosibirskaya Oblast'",
      "Omskaya Oblast'",
      "Orenburgskaya Oblast'",
      "Orlovskaya Oblast'",
      "Penzenskaya Oblast'",
      "Permskaya Oblast'",
      "Pskovskaya Oblast'",
      "Rostovskaya Oblast'",
      "Ryazanskaya Oblast'",
      "Sakhalinskaya Oblast'",
      'Samarskaya Oblast’',
      "Saratovskaya Oblast'",
      "Smolenskaya Oblast'",
      "Sverdlovskaya Oblast'",
      "Tambovskaya Oblast'",
      'Tomskaya Oblast’',
      "Tul'skaya Oblast'",
      "Tverskaya Oblast'",
      "Tyumenskaya Oblast'",
      "Ul'yanovskaya Oblast'",
      "Vladimirskaya Oblast'",
      "Volgogradskaya Oblast'",
      "Vologodskaya Oblast'",
      "Voronezhskaya Oblast'",
      "Yaroslavskaya Oblast'",
      'Moskva',
      'Sankt-Peterburg',
      "Yevreyskaya avtonomnaya oblast'",
      'Aginskiy Buryatskiy avtonomnyy okrug',
      'Chukotskiy avtonomnyy okrug',
      'Evenkiyskiy avtonomnyy okrug',
      'Khanty-Mansiyskiy avtonomnyy okrug',
      'Komi-Permyatskiy avtonomnyy okrug',
      'Koryakskiy avtonomnyy okrug',
      'Nenetskiy avtonomnyy okrug',
      'Taymyrskiy (Dolgano-Nenetskiy) avtonomnyy okrug',
      'Ust’-Ordynskiy Buryatskiy avtonomnyy okrug',
      'Yamalo-Nenetskiy avtonomnyy okrug',
    ],
  },
  {
    name: 'Rwanda',
    provinces: [
      'Butare',
      'Byumba',
      'Cyangugu',
      'Gikongoro',
      'Gisenyi',
      'Gitarama',
      'Kibungo',
      'Kibuye',
      'Kigali-Rural (Kigali y’ Icyaro)',
      'Kigali-Ville (Kilgali Ngari)',
      'Mutara',
      'Ruhengeri',
    ],
  },
  {
    name: 'St. Helena',
    provinces: ['Saint Helena', 'Ascension', 'Tristan da Cunha'],
  },
  {
    name: 'Saint Kitts & Nevis',
    provinces: ['Saint Kitts & Nevis'],
  },
  {
    name: 'Saint Lucia',
    provinces: ['Saint Lucia'],
  },
  {
    name: 'St. Pierre & Miquelon',
    provinces: ['St. Pierre & Miquelon'],
  },
  {
    name: 'St. Vincent & the Grenadines',
    provinces: ['St. Vincent & the Grenadines'],
  },
  {
    name: 'Samoa',
    provinces: [
      "A'ana",
      'Aiga-i-le-Tai',
      'Atua',
      "Fa'asaleleaga",
      "Gaga'emauga",
      'Gagaifomauga',
      'Palauli',
      "Satupa'itea",
      'Tuamasaga',
      "Va'a-o-Fonoti",
      'Vaisigano',
    ],
  },
  {
    name: 'San Marino',
    provinces: ['San Marino'],
  },
  {
    name: 'Sao Tome & Principe',
    provinces: ['Príncipe', 'Sāo Tomé'],
  },
  {
    name: 'Saudi Arabia',
    provinces: [
      'Al Bāḩah',
      'Al Ḩudūd ash Shamālīyah',
      'Al Jawf',
      'Al Madīnah',
      'Al Qaşim',
      'Ar Riyāḑ',
      'Ash Sharqīyah',
      '‘Asīr',
      "Ḩā'il",
      'Jīzān',
      'Makkah',
      'Najrān',
      'Tabūk',
    ],
  },
  {
    name: 'Senegal',
    provinces: [
      'Dakar',
      'Diourbel',
      'Fatick',
      'Kaolack',
      'Kolda',
      'Louga',
      'Saint-Louis',
      'Tambacounda',
      'Thiès',
      'Ziguinchor',
    ],
  },
  {
    name: 'Seychelles',
    provinces: ['Seychelles'],
  },
  {
    name: 'Sierra Leone',
    provinces: ['Western Area (Freetown)', 'Eastern', 'Northern', 'Southern'],
  },
  {
    name: 'Singapore',
    provinces: ['Singapore'],
  },
  {
    name: 'Slovak Republic',
    provinces: [
      'Banskobystrický kraj',
      'Bratislavský kraj',
      'Košický kraj',
      'Nitriansky kraj',
      'Prešovský kraj',
      'Trenčiansky kraj',
      'Trnavský kraj',
      'Žilinský kraj',
    ],
  },
  {
    name: 'Slovenia',
    provinces: [
      'Dolenjska',
      'Gorenjska',
      'Goriška',
      'Koroška',
      'Notranjsko-kraška',
      'Obalno-kraška',
      'Osrednjeslovenska',
      'Podravska',
      'Pomurska',
      'Savinjska',
      'Spodnjeposavska',
      'Zasavska',
    ],
  },
  {
    name: 'Solomon Islands',
    provinces: [
      'Capital Territory (Honiara)',
      'Central',
      'Guadalcanal',
      'Isabel',
      'Makira',
      'Malaita',
      'Temotu',
      'Western',
    ],
  },
  {
    name: 'Somalia',
    provinces: [
      'Awdal',
      'Bakool',
      'Banaadir',
      'Bari',
      'BaY',
      'Galguduud',
      'Gedo',
      'Hiiraan',
      'Jubbada Dhexe',
      'Jubbada Hoose',
      'Mudug',
      'Nugaal',
      'Sanaag',
      'Shabeellaha Dhexe',
      'Shabeellaha Hoose',
      'Sool',
      'Togdheer',
      'Woqooyi Galbeed',
    ],
  },
  {
    name: 'South Africa',
    provinces: [
      'Eastern Cape (Oos-Kaap)',
      'Free State (Vrystaat)',
      'Gauteng',
      'Kwazulu-Natal',
      'Mpumalanga',
      'Northern Cape (Noord-Kaap)',
      'Northern Province (Noordelike Provinsie)',
      'North-West (Noord-Wes)',
      'Western Cape (Wes-Kaap)',
    ],
  },
  {
    name: 'S.Georgia & S.Sandwich Islands',
    provinces: ['S.Georgia & S.Sandwich Islands'],
  },
  {
    name: 'Spain',
    provinces: [
      'Andalucía',
      'Almería',
      'Cádiz',
      'Córdoba',
      'Granada',
      'Huelva',
      'Jaén',
      'Málaga',
      'Sevilla',
      'Aragón',
      'Huesca',
      'Teruel',
      'Zaragoza',
      'Asturias',
      'Canarias',
      'Las Palmas',
      'Santa Cruz De Tenerife',
      'Cantabria',
      'Castilla-La Mancha',
      'Albacete',
      'Ciudad Real',
      'Cuenca',
      'Guadalajara',
      'Toledo',
      'Castilla y León',
      'Ávila',
      'Burgos',
      'León',
      'Palencia',
      'Salamanca',
      'Segovia',
      'Soria',
      'Valladolid',
      'Zamora',
      'Cataluña',
      'Barcelona',
      'Gerona',
      'Lérida',
      'Tarragona',
      'Extremadura',
      'Badajoz',
      'Cáceres',
      'Galicia',
      'La Coruña',
      'Lugo',
      'Orense',
      'Pontevedra',
      'Baleares',
      'La Rioja',
      'Madrid',
      'Murcia',
      'Navarra',
      'País Vasco',
      'Álava',
      'Guipúzcoa',
      'Vizcaya',
      'Valenciana, Comunidad',
      'Alicante',
      'Castellón',
      'Valencia',
    ],
  },
  {
    name: 'Sri Lanka',
    provinces: [
      'Basnahira Palata (Western Province)',
      'Colombo',
      'Gampaha',
      'Kalutara',
      'Dakunu Palata (Southern Province)',
      'Galle',
      'Hambantota',
      'Matara',
      'Madhyama Palata (Central Province)',
      'Kandy',
      'Matale',
      'Nuwara Eliya',
      'Negenahira Palata (Eastern Province)',
      'Arnpara',
      'Batticaloa',
      'Trincomalee',
      'Sabaragamuwa Palata',
      'Kegalla',
      'Ratnapura',
      'Uturumeda Palata (North Central Province)',
      'Anuradhapura',
      'Polonnaruwa',
      'Uturu Palata (Northern Province)',
      'Jaffna',
      'Kilinochchi',
      'Mannar',
      'Mullaittivu',
      'Vavuniya',
      'Uva Palata',
      'Badulla',
      'Monaragala',
      'Wayamba Palata (North Western Province)',
      'Kurunegala',
      'Puttalam',
    ],
  },
  {
    name: 'Sudan',
    provinces: [
      'A‘ālī an Nīl',
      'Al Baḩr al Aḩmar',
      'Al Buḩayrāt',
      'Al Jazīrah',
      'Al Kharţūm',
      'Al Qaḑārif',
      'Al Waḩdah',
      'An Nīl',
      'An Nīl al Abyaḑ',
      'An Nīl al Azraq',
      'Ash Shamālīyah',
      'Baḩr al Jabal',
      "Gharb al Istiwā'īyah",
      'Gharb Baḩr al Ghazāl',
      'Gharb Dārfūr',
      'Gharb Kurdufān',
      'Janūb Dārfūr',
      'Janūb Kurdufān',
      'Jūnqalī',
      'Kassalā',
      'Shamāl Baḩr al Ghazāl',
      'Shamāl Dārfūr',
      'Shamāl Kurdufān',
      "Sharq al Istiwā'iyah",
      'Sinnār',
      'Wārāb',
    ],
  },
  {
    name: 'Suriname',
    provinces: [
      'Brokopondo',
      'Commewijne',
      'Coronie',
      'Marowijne',
      'Nickerie',
      'Para',
      'Paramaribo',
      'Saramacca',
      'Sipaliwini',
      'Wanica',
    ],
  },
  {
    name: 'Svalbard & Jan Mayen Islands',
    provinces: ['Svalbard & Jan Mayen Islands'],
  },
  {
    name: 'Swaziland',
    provinces: ['Hhohho', 'Lubombo', 'Manzini', 'Shiselweni'],
  },
  {
    name: 'Sweden',
    provinces: [
      'Blekinge län',
      'Dalarnas län',
      'Gotlands län',
      'Gävleborgs län',
      'Hallands län',
      'Jämtlands län',
      'Jönköpings län',
      'Kalmar län',
      'Kronobergs län',
      'Norrbottens län',
      'Skåne län',
      'Stockholms län',
      'Södermanlands län',
      'Uppsala län',
      'Värmlands län',
      'Västerbottens län',
      'Västernorrlands län',
      'Västmanlands län',
      'Västra Götalands län',
      'Örebro län',
      'Östergötlands län',
    ],
  },
  {
    name: 'Switzerland',
    provinces: [
      'Aargau',
      'Appenzell Ausser-Rhoden',
      'Appenzell Inner-Rhoden',
      'Basel-Landschaft',
      'Basel-Stadt',
      'Bern',
      'Freiburg',
      'Geneve',
      'Glarus',
      'Graubünden',
      'Jura',
      'Luzern',
      'Neuchatel',
      'Nidwalden',
      'Obwalden',
      'Sankt Gallen',
      'Schaffhausen',
      'Schwyz',
      'Solothurn',
      'Thurgau',
      'Ticino',
      'Uri',
      'Wallis',
      'Vaud',
      'Zug',
      'Zürich',
    ],
  },
  {
    name: 'Syria',
    provinces: [
      'Al Ḩasakah',
      'Al Lādhiqīyah',
      'Al Qunayţirah',
      'Ar Raqqah',
      "As Suwaydā'",
      'Dar’ā',
      'Dayr az Zawr',
      'Dimashq',
      'Ḩalab',
      'Ḩamāh',
      'Ḩimş',
      'Idlib',
      'Rīf Dimashq',
      'Ţarţūs',
    ],
  },
  {
    name: 'Taiwan',
    provinces: [
      'Kaohsiung',
      'Taipei',
      'Chiayi',
      'Hsinchu',
      'Keelung',
      'Taichung',
      'Tainan',
      'Changhua',
      'Hualien',
      'Ilan',
      'Miaoli',
      'Nantou',
      'Penghu',
      'Pingtung',
      'Taitung',
      'Taoyuan',
      'Yunlin',
    ],
  },
  {
    name: 'Tajikistan',
    provinces: ['Karategin', 'Khatlon', 'Leninabad', 'Gorno-Badakhshan'],
  },
  {
    name: 'Tanzania',
    provinces: [
      'Arusha',
      'Dar-es-Salaam',
      'Dodoma',
      'Iringa',
      'Kagera',
      'Kaskazini Pemba (Pemba North)',
      'Kaskazini Unguja (Zanzibar North)',
      'Kigoma',
      'Kilimanjaro',
      'Kusini Pemba (Pemba South)',
      'Kusini Unguja (Zanzibar South)',
      'Lindi',
      'Mara',
      'Mbeya',
      'Mjini Magharibi (Zanzibar West)',
      'Morogoro',
      'Mtwara',
      'Mwanza',
      'Pwani (Coast)',
      'Rukwa',
      'Ruvuma',
      'Shinyanga',
      'Singida',
      'Tabora',
      'Tanga',
    ],
  },
  {
    name: 'Thailand',
    provinces: [
      'Krung Thep Maha Nakhon [Bangkok]',
      'Phatthaya',
      'Amnat Charoen',
      'Ang Thong',
      'Buri Ram',
      'Chachoengsao',
      'Chai Nat',
      'Chaiyaphum',
      'Chanthaburi',
      'Chiang Mai',
      'Chiang Rai',
      'Chon Buri',
      'Chumphon',
      'Kalasin',
      'Kamphaeng Phet',
      'Kanchanaburi',
      'Khon Kaen',
      'Krabi',
      'Lampang',
      'Lamphun',
      'Loei',
      'Lop Buri',
      'Mae Hong Son',
      'Maha Sarakham',
      'Mukdahan',
      'Nakhon Nayok',
      'Nakhon Pathom',
      'Nakhon Phanom',
      'Nakhon Ratchasima',
      'Nakhon Sawan',
      'Nakhon Si Thammarat',
      'Nan',
      'Narathiwat',
      'Nong Bua Lam Phu',
      'Nong Khai',
      'Nonthaburi',
      'Pathum Thani',
      'Pattani',
      'Phangnga',
      'Phatthalung',
      'Phayao',
      'Phetchabun',
      'Phetchaburi',
      'Phichit',
      'Phitsanulok',
      'Phrae',
      'Phra Nakhon Si Ayutthaya',
      'Phuket',
      'Prachin Buri',
      'Prachuap Khiri Khan',
      'Ranong',
      'Ratchaburi',
      'Rayong',
      'Roi Et',
      'Sa Kaeo',
      'Sakon Nakhon',
      'Samut Prakan',
      'Samut Sakhon',
      'Samut Songkhram',
      'Saraburi',
      'Satun',
      'Sing Buri',
      'Si Sa Ket',
      'Songkhla',
      'Sukhothai',
      'Suphan Buri',
      'Surat Thani',
      'Surin',
      'Tak',
      'Trang',
      'Trat',
      'Ubon Ratchathani',
      'Udon Thani',
      'Uthai Thani',
      'Uttaradit',
      'Yala',
      'Yasothon',
    ],
  },
  {
    name: 'Togo',
    provinces: ['Centre', 'Kara', 'Maritime (Région)', 'Plateaux', 'Savannes'],
  },
  {
    name: 'Tokelau',
    provinces: ['Tokelau'],
  },
  {
    name: 'Tonga',
    provinces: ['Tonga'],
  },
  {
    name: 'Trinidad & Tobago',
    provinces: [
      'Couva-Tabaquite-Talparo',
      'Diego Martin',
      'Eastern Tobago',
      'Penal-Debe',
      'Princes Town',
      'Rio Claro-Mayaro',
      'Sangre Grande',
      'San Juan-Laventille',
      'Siparia',
      'Tunapuna-Piarco',
      'Western Tobago',
      'Arima',
      'Chaguanas',
      'Point Fortin',
      'Port of Spain',
      'San Fernando',
    ],
  },
  {
    name: 'Tunisia',
    provinces: [
      'Béja',
      'Ben Arous',
      'Bizerte',
      'Gabès',
      'Gafsa',
      'Jendouba',
      'Kairouan',
      'Kasserine',
      'Kebili',
      "L'Ariana",
      'Le Kef',
      'Mahdia',
      'Medenine',
      'Monastir',
      'Nabeul',
      'Sfax',
      'Sidi Bouzid',
      'Siliana',
      'Sousse',
      'Tataouine',
      'Tozeur',
      'Tunis',
      'Zaghouan',
    ],
  },
  {
    name: 'Turkey',
    provinces: [
      'Adana',
      'Adiyaman',
      'Afyon',
      'Ağrı',
      'Aksaray',
      'Amasya',
      'Ankara',
      'Antalya',
      'Ardahan',
      'Artvin',
      'Aydin',
      'Balıkesir',
      'Bartın',
      'Batman',
      'Bayburt',
      'Bilecik',
      'Bingöl',
      'Bitlis',
      'Bolu',
      'Burdur',
      'Bursa',
      'Çanakkale',
      'Çankırı',
      'Çorum',
      'Denizli',
      'Diyarbakır',
      'Edirne',
      'Elaziğ',
      'Erzincan',
      'Erzurum',
      'Eskişehir',
      'Gaziantep',
      'Giresun',
      'Gümüşhane',
      'Hakkari',
      'Hatay',
      'Iğdir',
      'Isparta',
      'İçel',
      'İstanbul',
      'İzmir',
      'Kahramanmaraş',
      'Karabük',
      'Karaman',
      'Kars',
      'Kastamonu',
      'Kayseri',
      'Kırıkkale',
      'Kırklareli',
      'Kırşehir',
      'Kilis',
      'Kocaeli',
      'Konya',
      'Kütahya',
      'Malatya',
      'Manisa',
      'Mardin',
      'Muğla',
      'Muş',
      'Nevşehir',
      'Niğde',
      'Ordu',
      'Rize',
      'Sakarya',
      'Samsun',
      'Siirt',
      'Sinop',
      'Sivas',
      'Şanlıurfa',
      'Şirnak',
      'Tekirdağ',
      'Tokat',
      'Trabzon',
      'Tunceli',
      'Uşak',
      'Van',
      'Yalova',
      'Yozgat',
      'Zonguldak',
    ],
  },
  {
    name: 'Turkmenistan',
    provinces: ['Ahal', 'Balkan', 'Daşhowuz', 'Lebap', 'Mary'],
  },
  {
    name: 'Turks & Caicos Islands',
    provinces: ['Turks & Caicos Islands'],
  },
  {
    name: 'Tuvalu',
    provinces: ['Tuvalu'],
  },
  {
    name: 'Uganda',
    provinces: [
      'Apac',
      'Arua',
      'Bundibugyo',
      'Bushenyi',
      'Gulu',
      'Hoima',
      'Iganga',
      'Jinja',
      'Kabale',
      'Kabarole',
      'Kalangala',
      'Kampala',
      'Kamuli',
      'Kapchorwa',
      'Kasese',
      'Kibaale',
      'Kiboga',
      'Kisoro',
      'Kitgum',
      'Kotido',
      'Kumi',
      'Lira',
      'Luwero',
      'Masaka',
      'Masindi',
      'Mbale',
      'Mbarara',
      'Moroto',
      'Moyo',
      'Mpigi',
      'Mubende',
      'Mukono',
      'Nebbi',
      'Ntungamo',
      'Pallisa',
      'Rakai',
      'Rukungiri',
      'Soroti',
      'Tororo',
    ],
  },
  {
    name: 'Ukraine',
    provinces: [
      "Cherkas'ka Oblast'",
      "Chernihivs'ka Oblast'",
      "Chernivets'ka Oblast'",
      "Dnipropetrovs'ka Oblast'",
      "Donets'ka Oblast'",
      "Ivano-Frankivs'ka Oblast'",
      "Kharkivs'ka Oblast'",
      "Khersons'ka Oblast'",
      "Khmel'nyts'ka Oblast'",
      "Kirovohrads'ka Oblast'",
      "Kyïvs'ka Oblast'",
      "Luhans'ka Oblast'",
      "L'vivs'ka Oblast'",
      "Mykolaïvs'ka Oblast'",
      "Odes'ka Oblast'",
      "Poltavs'ka Oblast'",
      "Rivnens'ka Oblast'",
      "Sums'ka Oblast'",
      "Ternopil's'ka Oblast'",
      "Vinnyts'ka Oblast'",
      "Volyns'ka Oblast'",
      "Zakarpats'ka Oblast'",
      "Zaporiz'ka Oblast'",
      "Zhytomyrs'ka Oblast'",
      'Respublika Krym',
      'Kyïv',
      "Sevastopol'",
    ],
  },
  {
    name: 'United Arab Emirates',
    provinces: [
      'Abū Zaby (Abu Dhabi)',
      '‘Ajmān',
      'Al Fujayrah',
      'Ash Shāriqah (Sharjah)',
      'Dubayy (Dubai)',
      "R'as al Khaymah",
      'Umm al Qaywayn',
    ],
  },
  {
    name: 'United States',
    provinces: [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
      'District of Columbia',
      'American Samoa',
      'Guam',
      'Northern Mariana Islands',
      'Puerto Rico',
      'United States Minor Outlying Islands',
      'Virgin Islands, U.S.',
    ],
  },
  {
    name: 'Uruguay',
    provinces: [
      'Artigas',
      'Canelones',
      'Cerro Largo',
      'Colonia',
      'Durazno',
      'Flores',
      'Florida',
      'Lavalleja',
      'Maldonado',
      'Montevideo',
      'Paysandú',
      'Río Negro',
      'Rivera',
      'Rocha',
      'Salto',
      'San José',
      'Soriano',
      'Tacuarembó',
      'Treinta y Tres',
    ],
  },
  {
    name: 'Uzbekistan',
    provinces: [
      'Qoraqalpoghiston Respublikasi (Karakalpakstan, Respublika)',
      'Andijon (Andizhan)',
      'Bukhoro (Bukhara)',
      'Farghona (Fergana)',
      'Jizzakh (Dzhizak)',
      'Khorazm (Khorezm)',
      'Namangan',
      'Nawoiy (Navoi)',
      "Qashqadaryo (Kashkadar'ya)",
      'Samarqand (Samarkand)',
      "Sirdaryo (Syrdar'ya)",
      "Surkhondaryo (Surkhandar'ya)",
      'Toshkent (Tashkent)',
    ],
  },
  {
    name: 'Vanuatu',
    provinces: ['Malampa', 'Pénama', 'Sanma', 'Shéfa', 'Taféa', 'Torba'],
  },
  {
    name: 'Venezuela',
    provinces: [
      'Distrito Federal',
      'Anzoátegui',
      'Apure',
      'Aragua',
      'Barinas',
      'Bolívar',
      'Carabobo',
      'Cojedes',
      'Falcón',
      'Guárico',
      'Lara',
      'Mérida',
      'Miranda',
      'Monagas',
      'Nueva Esparta',
      'Portuguesa',
      'Sucre',
      'Táchira',
      'Trujillo',
      'Yaracuy',
      'Zulia',
      'Amazonas',
      'Delta Amacuro',
      'Dependencias Federales',
    ],
  },
  {
    name: 'Viet Nam',
    provinces: [
      'An Giang',
      'Bat Can',
      'Bat Giang',
      'Bat Lieu',
      'Bat Ninh',
      'Ba Ria - Vung Tau',
      'Ben Tre',
      'Binh Dinh',
      'Binh Duong',
      'Binh Phuoc',
      'Binh Thuan',
      'Ca Mau',
      'Can Tho',
      'Cao Bang',
      'Dac Lac',
      'Da Nang, thanh pho',
      'Dong Nai',
      'Dong Thap',
      'Gia Lai',
      'Ha Giang',
      'Hai Duong',
      'Hai Phong, thanh pho',
      'Ha Nam',
      'Ha Noi, thu do',
      'Ha Tay',
      'Ha Tinh',
      'Hoa Binh',
      'Ho Chi Minh, thanh po [Sai Gon]',
      'Hung Yen',
      'Khanh Hoa',
      'Kien Giang',
      'Kon Turn',
      'Lai Chau',
      'Lam Dong',
      'Lang Son',
      'Lao Cai',
      'Long An',
      'Nam Dinh',
      'Nghe An',
      'Ninh Binh',
      'Ninh Thuan',
      'Phu Tho',
      'Phu Yen',
      'Quang Ninh',
      'Quang Nam',
      'Quang Ngai',
      'Quang Tri',
      'Sec Trang',
      'Son La',
      'Tay Ninh',
      'Thai Binh',
      'Thai Nguyen',
      'Thanh Hoa',
      'Thua Thien-Hue',
      'Tien Giang',
      'Tra Vinh',
      'Tuyen Quang',
      'Vinh Long',
      'Vinh Yen',
      'Yen Bai',
    ],
  },
  {
    name: 'Virgin Islands (British)',
    provinces: ['Virgin Islands (British)'],
  },
  {
    name: 'Virgin Islands (U.S.)',
    provinces: ['Virgin Islands (U.S.)'],
  },
  {
    name: 'Wallis & Futuna Islands',
    provinces: ['Wallis & Futuna Islands'],
  },
  {
    name: 'Western Sahara',
    provinces: ['Western Sahara'],
  },
  {
    name: 'Yemen',
    provinces: [
      'Abyān',
      '‘Adan',
      "Al Bayḑā'",
      'Al Ḩudaydah',
      'Al Jawf',
      'Al Mahrah',
      'Al Maḩwit',
      'Dhamār',
      'Ḩaḑramawt',
      'Ḩajjah',
      'Ibb',
      'Laḩij',
      "Ma'rib",
      "Şa'dah",
      "Şan‘ā'",
      'Shabwah',
      'Ta‘izz',
    ],
  },
  {
    name: 'Yugoslavia',
    provinces: ['Crna Gora', 'Srbija', 'Kosovo-Metohija', 'Vojvodina'],
  },
  {
    name: 'Zambia',
    provinces: [
      'Central',
      'Copperbelt',
      'Eastern',
      'Luapula',
      'Lusaka',
      'Northern',
      'North-Western',
      'Southern',
      'Western',
    ],
  },
  {
    name: 'Zimbabwe',
    provinces: [
      'Bulawayo',
      'Harare',
      'Manicaland',
      'Mashonaland Central',
      'Mashonaland East',
      'Mashonaland West',
      'Masvingo',
      'Matabeleland North',
      'Matabeleland South',
      'Midlands',
    ],
  },
];

export const GENDERS = ['Maschile', 'Femminile', 'Non-binary'] as const;
export type Gender = (typeof GENDERS)[number];
